### ISSUE TITLE
helm is now everywhere instead of completing-read?

### ISSUE THREAD

**Issue by vspinu** [emacs-helm/helm#1063]
I have just upgraded and helm is all over the place instead of the default completing-read. 

I am looking at `helm-completing-read-handlers-alist` and ,if I understand correctly, for all other commands helm should pass control to the next function, but that is not happening in the current version.

**Comment by thierryvolpiatto** [comment]
Vitalie Spinu <notifications@github.com> writes:

> I have just upgraded and helm is all over the place instead of the default completing-read.
>
> I am looking at helm-completing-read-handlers-alist and ,if I
> understand correctly, for all other commands helm should pass control
> to the next function,

Hmm, not sure to understand what you mean with "next function".

Each command in emacs that contain a completing-read will use helm
completion for this completing-read when helm-mode is enabled.
helm-completing-read-handlers-alist is here to allow changing this when
helm-mode is enabled.
Take for example find-file-read-only, it is using currently helm completion.
if I do:

(add-to-list 'helm-completing-read-handlers-alist '(find-file-read-only . ido))

Now I have ido completion (no need to enable ido-mode).

Now I modify it:

(setcdr (assoc 'find-file-read-only helm-completing-read-handlers-alist)
nil)

Now find-file-read-only is using vanilla emacs completion.

If you remove now find-file-read-only from the alist, you are back to
helm completion.

If you want to give it a new value instead of ido or nil, you will have
to build a function that _replace the completing-read_ but NOT the
function find-file-read-only.

> but that is not happening in the current version.

helm-mode is working fine actually, can you provide examples on where it
doesn't work?

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by vspinu** [comment]
> Hmm, not sure to understand what you mean with "next function". 

As a value of `completing-read-function` I see

```
      [apply helm--completing-read-default completing-read-default nil]
      4 nil]
```

So I guessed that `completing-read-default` is the "next function". 

> Each command in emacs that contain a completing-read will use helm completion for this completing-read when helm-mode is enabled.

That was it. I accidentally enabled helm-mode in my config.  Thanks!


> helm-mode is working fine actually, can you provide examples on where it
doesn't work?

Actually yes. With IDO I am used to entering empty option with C-j. In helm C-j is bound to `helm-execute-persistent-action`.  For example with `(completing-read "lala> " '("aa" "bb" "cc"))` how do I insert an empty string?

**Comment by thierryvolpiatto** [comment]
Vitalie Spinu <notifications@github.com> writes:

> Actually yes. With IDO I am used to entering empty option with C-j. In
> helm C-j is bound to helm-execute-persistent-action. For example with
> (completing-read "lala> " '("aa" "bb" "cc")) how do I insert an
> empty string?

If you read carefully your mode-line, the answer is not far ;-)

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by vspinu** [comment]
> If you read carefully your mode-line, the answer is not far ;-)

LOL. Thanks!
