### ISSUE TITLE
Attempting file operations in helm-find-files with sr-speedbar or neotree open leaves a small window behind

### ISSUE THREAD

**Issue by nivekuil** [emacs-helm/helm#1068]
To replicate: start emacs (tested with emacs -Q), open sr-speedbar or neotree. Call `helm-find-files`, press M-C or M-R, and then C-g or finish the operation. There will be a small, vertically split window left at the bottom.

**Comment by thierryvolpiatto** [comment]
Kevin Liu <notifications@github.com> writes:

> To replicate: have sr-speedbar or neotree open.

Don't know neotree.
But sr-speedbar is a regular cause of bugs due to its defadvices.
So I will not try to fix this, my advice, just do not use such packages.

> Call helm-find-files, press M-C or M-R, and then C-g or finish the
> operation. There will be a small, vertically split window left at the
> bottom.

Of course pop-to-buffer, delete-window, delete-other-windows and may be
others are adviced, what can I do ?
Nothing.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
