### ISSUE TITLE
how to write helm source?

### ISSUE THREAD

**Issue by vjohansen** [emacs-helm/helm#1069]
where is the documentation for writing a helm source?

**Comment by xuchunyang** [comment]
https://github.com/emacs-helm/helm/wiki#25-developping-using-helm-framework

**Comment by vjohansen** [comment]
Thanks. 

So there is not so much documentation then.

I would like to see an explanation of helm-candidates-buffer. When should it be used and when should the different arguments be used.

**Comment by thierryvolpiatto** [comment]
Vagn Johansen <notifications@github.com> writes:

> Thanks.
>
> So there is not so much documentation then.

Yes it is not finished.

> I would like to see an explanation of helm-candidates-buffer. When
> should it be used and when should the different arguments be used.

You mean `helm-candidate-buffer' I guess.
You should not have to use this, use instead
`helm-init-candidates-in-buffer'.
Even simpler is to use the :data slot with the `helm-source-in-buffer'
class.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by vjohansen** [comment]
What are the scenarios for the different values of BUFFER in helm-init-candidates-in-buffer?

**Comment by thierryvolpiatto** [comment]
Vagn Johansen <notifications@github.com> writes:

> What are the scenarios for the different values of BUFFER in helm-init-candidates-in-buffer?

If you use a single source using the in-buffer method in your helm call,
'global is probaly (most of the time) enough, :data use this actually to set
things up (this may change).

But if for the same helm call you use more than one source and these
sources are all (or at least 2) using in-buffer method, then you should
use 'local with the :init slot, otherwise all your sources will try to
share the same data buffer.

Of course you can use also a plain string to name and differency your buffers.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
