### ISSUE TITLE
helm-completion-in-region-fuzzy-match not getting picked up

### ISSUE THREAD

**Issue by bling** [emacs-helm/helm#1074]
i have the variable set to `t`, but things like `describe-function` are still not fuzzy matching.  i had to manually add `:fuzzy-match t` to the `helm-completing-read-symbols` function for things to start working.

aside, is there an easy way to make fuzzy matching globally on by default?  i see that in helm-source there's a slot for fuzzy-match and if i set that to `t` it does what i want, but it's a pretty big defclass, so it's not a simple thing i could add to my config.  i'm unfamilar with defclass -- is there an easy way to change the default value of the slot?  thanks.

**Comment by thierryvolpiatto** [comment]
Bailey Ling <notifications@github.com> writes:

> i have the variable set to t, but things like describe-function are
> still not fuzzy matching.

describe-function have nothing to do with completion-in-region, this
variable doesn't affect this, it affect only completions that are using
completion-in-region mechanism like completion-at-point.

fuzzy-match is available in helm-mode only for this.

> i had to manually add :fuzzy-match t to the
> helm-completing-read-symbols function for things to start working.

Instead of modifying source code, you can write a function like
helm-completing-read-symbols (copy it) that handle fuzzy-match and add
it to helm-completing-read-handlers-alist for e.g describe-function.

This is if you really want to use describe-function/variable, but you
have better time using helm-apropos that support fuzzy-match, handle
variables, classes etc... and much more.

> aside, is there an easy way to make fuzzy matching globally on by
> default?

No and it is not wanted, fuzzy matching is good for certains things and
not others.

> i see that in helm-source there's a slot for fuzzy-match and if i set
> that to t it does what i want, but it's a pretty big defclass, so it's
> not a simple thing i could add to my config.

You should not change (never) the class definition, instead create your own
class that herit from one of these low-level classes.

> i'm unfamilar with defclass -- is there an easy way to change the
> default value of the slot?

When building the sources yes.

e.g

(helm :sources (helm-make-source "test" 'helm-source-sync
                 :candidates '(foa bar baz)
                 :fuzzy-match t)
      :buffer "*helm test*")

So you don't have to modify the class helm-source-sync to have fuzzy
matching happening in your new command.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by bling** [comment]
thanks for the detailed reply.

`helm-apropos` does search for a lot more and does fuzzy matching, but it's also slower than when i know for certain i want to look for a function or a variable.

> No and it is not wanted, fuzzy matching is good for certains things and
not others.

i can't be the only one that prefers fuzzy matching to everything else.  currently i scan the helm source code for `defcustom.*fuzzy` every so often and set all of them to `t` in my config.

i understand that i could create custom helm sources to do what i want, but unfortunately it would mean a lot of code in my config to define all the custom sources (and potentially new key bindings), and i was hoping i would able to avoid that with a 1 or 2 liner.

would you be open to a PR that introduces another `defvar` so that `helm-completing-read-symbols` can be set to t?

thanks!

**Comment by thierryvolpiatto** [comment]
Bailey Ling <notifications@github.com> writes:

> thanks for the detailed reply.
>
> helm-apropos does search for a lot more and does fuzzy matching, but
> it's also slower than when i know for certain i want to look for a
> function or a variable.

Depend on what you call slow, for me is fast enough to serve all my
needs when developing lisp code.

>     No and it is not wanted, fuzzy matching is good for certains things and
>     not others.
>    
> i can't be the only one that prefers fuzzy matching to everything
> else. currently i scan the helm source code for defcustom.*fuzzy every
> so often and set all of them to t in my config.
>
> i understand that i could create custom helm sources to do what i
> want, but unfortunately it would mean a lot of code in my config to
> define all the custom sources (and potentially new key bindings), and
> i was hoping i would able to avoid that with a 1 or 2 liner.

Of course was just FYI about usage of classes in case you want to write
something new.

> would you be open to a PR that introduces another defvar so that
> helm-completing-read-symbols can be set to t?

Fo this one yes, but not globally.
(Use a defcustom, not a defvar).

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
