### ISSUE TITLE
helm-find-files: C-. "Company not enabled"

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [emacs-helm/helm#1089]
I don't know exactly when this problem started, but I update Helm regularly. I am currently unable to use `C-.` to go one level up in the current path while in `helm-find-files`. I get the message `"Company not enabled"` in the minibuffer.

In case it helps I  am using:

`"GNU Emacs 25.0.50.1 (x86_64-apple-darwin14.3.0, NS appkit-1347.57 Version 10.10.3 (Build 14D136))  of 2015-06-03 on macbook-pro.bos.xxx.net"`

**Comment by thierryvolpiatto** [comment]
Amelio Vazquez-Reina <notifications@github.com> writes:

> I don't know when I started having this problem, but I update Helm
> regularly, and never had a problem invoking C-. to go one level up in
> the current path while helm-find-files. However, I currently get the
> message "Company not enabled" in the minibuffer.

`C-.' have been removed in helm-find-files, use instead `C-l' or left
arrow (need helm-ff-lynx-style-map enabled).

So now when you press C-. you use the global binding which is apparently
bound to some company command.

`C-.' have been removed because it is now rarely used (most people use
C-l) and it is not working in emacs -nw.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by amelio-vazquez-reina** [comment]
Sounds great. Thanks @thierryvolpiatto
