### ISSUE TITLE
Helm-etags-select gives inconsequent filter results. 

### ISSUE THREAD

**Issue by ReneFroger** [emacs-helm/helm#1130]
I made a clip, to make clear what my issue is. I start `helm-etags-select`.

![test](https://cloud.githubusercontent.com/assets/5211845/9278209/8732cee4-42af-11e5-893f-a4d4745fc685.gif)

Then I type `function`, and point out I would like to get the line `public function fWeekendWerkdagChecker`. 

So I type further `function fWeekendWerkdagChecker`, but it don't get filtered out. 

Then I run another example.I get cAjaxMeldingen, when I type `cAjax`. But what if I type `class cAjax`. Then I get nothing. Any suggestion what caused this behaviour?

**Comment by thierryvolpiatto** [comment]
ReneFroger <notifications@github.com> writes:

>
> Then I run another example.I get cAjaxMeldingen, when I type
> cAjax. But what if I type class cAjax. Then I get nothing. Any
> suggestion what caused this behaviour?

What happen is when you typed cAjax it was matching because matching was
set to match only on the relevant part of your tag, that is "cAjax..."
and ignore "Class".

I have commited a change that allow you customizing this behavior, now
with default setting, you should match both "Class cAjax" and "cAjax".

See the variable `helm-etags-match-part-only' to customize this.

PS: helm use a smart case-fold-search by default (see
helm-case-fold-search for more info) so you don't have to specify upcase
letters, For e.g "cAjax" you can write "cajax" unless there is other
candidate non-upcased and you want to be sure to match exactly "cAjax".

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by ReneFroger** [comment]
I just tested it, and it worked fine. Thanks for the support, it's appreciated!
