### ISSUE TITLE
helm-imenu doesn't work if point is on a symbol

### ISSUE THREAD

**Issue by Wilfred** [emacs-helm/helm#1134]
Given the python code, where `|` is point:

```python
def foo():
    pass

def foobar|():
    pass
```

Running `M-x helm-imenu` simply moves point to the beginning of the line. Running `M-x helm-imenu` again behaves as expected, offering a choice of symbols to jump to.

`M-x imenu` does not have this bug, so I think it's a helm issue.

**Comment by thierryvolpiatto** [comment]
Wilfred Hughes <notifications@github.com> writes:

> Given the python code, where | is point:
>
> def foo():
>     pass
>
> def foobar|():
>     pass
>
> Running M-x helm-imenu simply moves point to the beginning of the
> line. Running M-x helm-imenu again behaves as expected, offering a
> choice of symbols to jump to.
>
> M-x imenu does not have this bug, so I think it's a helm issue.

imenu propose the symbol at point as default, helm is doing the same,
but jump to it automatically because helm-source-imenu is member of
helm-sources-using-default-as-input.
So when you are already at symbol helm jump to the symbol at beginning
of line.  It is annoying when cursor is on a definition of symbol, but
really useful when you search the definition of the symbol at point.

I may use a preselection in such cases in the future for such cases.
 
You can disable this by customizing helm-sources-using-default-as-input.
(your default will still be accessible with M-n)

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Wilfred Hughes <notifications@github.com> writes:

> M-x imenu does not have this bug, so I think it's a helm issue.

BTW I see imenu have a big bug that is it give default as a string
instead of providing a cons cell so it it not possible to jump to
default (no marker provided).  This is an emacs bug.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by Wilfred** [comment]
Aha, that explains the current behaviour. In the following situation, point jumps directly to `def foo` for the same reason.

```python
def foo():
    pass

def foobar():
    foo|()
```

I use imenu for getting an overview of a big file rather than jumping to a definition (I use tags for jumping to a definition).

Would you be willing to change the default behaviour of `helm-imenu` to not jump, even if there's a symbol at point? I totally understand that the current behaviour is useful, so perhaps the best solution is to have two separate commands? Something like `helm-imenu` and `helm-imenu-at-point` (or `helm-imenu-select` and `helm-imenu`).

**Comment by thierryvolpiatto** [comment]
Wilfred Hughes <notifications@github.com> writes:

> Aha, that explains the current behaviour. In the following situation, point jumps directly to def foo for the same reason.
>
> def foo():
>     pass
>
> def foobar():
>     foo|()
>
> I use imenu for getting an overview of a big file rather than jumping
> to a definition (I use tags for jumping to a definition).
>
> Would you be willing to change the default behaviour of helm-imenu to
> not jump, even if there's a symbol at point? I totally understand that
> the current behaviour is useful, so perhaps the best solution is to
> have two separate commands? Something like helm-imenu and
> helm-imenu-at-point (or helm-imenu-select and helm-imenu).

No, up to you to configure this, remove helm-imenu from
helm-sources-using-default-as-input, the symbol at point will be
preselected instead of jumping to it.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by Wilfred** [comment]
Thanks, that does the trick:

```lisp
(setq helm-sources-using-default-as-input
        (remove 'helm-source-imenu helm-sources-using-default-as-input))
```

Would you be open to a pull request that added a `helm-imenu-select` command? Currently, I have to choose whether I want the symbol preselected or not -- I can't have both.

**Comment by thierryvolpiatto** [comment]
Wilfred Hughes <notifications@github.com> writes:

> Thanks, that does the trick:
>
> (setq helm-sources-using-default-as-input
>         (remove 'helm-source-imenu helm-sources-using-default-as-input))
>
> Would you be open to a pull request that added a helm-imenu-select
> command? Currently, I have to choose whether I want the symbol
> preselected or not -- I can't have both.

No, I want to avoid having many commands doing more or less the same
thing.

what you can do is using helm-imenu-in-all-buffers with one
behavior and helm-imenu (or helm-semantic-or-imenu) with the other
behavior.

What I want to have is using preselection when we are already on the
definition instead of jumping at bol and jump to definition otherwise.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
> What I want to have is using preselection when we are already on the definition instead of jumping at > bol and jump to definition otherwise.

Should be fixed now.

**Comment by thierryvolpiatto** [comment]
> Would you be open to a pull request that added a helm-imenu-choose command? Currently, I have > to decide whether I want the symbol preselected or not -- I can't have both.

I made the preselection always available (not only with default as input) so even with default as input disabled, you will be able to jump to definition with RET.

**Comment by Wilfred** [comment]
Brilliant, thank you!
