### ISSUE TITLE
helm-autoloads.el gets loaded twice if install helm via package.el

### ISSUE THREAD

**Issue by xuchunyang** [emacs-helm/helm#1156]
`package.el` loads every package's autoload file during its initialization phase, so `helm-autoloads.el` gets loaded for the first time.

but `helm-config.el` will load it again with:

```elisp
;;; Load the autoload file
;;  It should have been generated either by
;;  package.el or the make file.

(load "helm-autoloads" nil t)
```

though loading the same file twice doesn't introduce any real problem, except maybe increasing Emacs init time a little bit.

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

> package.el loads every package's autoload file during its initialization phase, so helm-autoloads.el gets loaded for the first time.
>
> but helm-config.el will load it again with:
>
> ;;; Load the autoload file
> ;;  It should have been generated either by
> ;;  package.el or the make file.
>
> (load "helm-autoloads" nil t)
>
> though loading the same file twice doesn't introduce any real problem, except maybe increasing Emacs init time a little bit.

I know about this and it need to be fixed, but for now we can't remove
this, it is needed for people installing from git (with makefile).
There is no urgency, loading such a file is really fast.
And we can't use `require', because for some reasons package.el is not
creating a `provide' when creating the file.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by xuchunyang** [comment]
> I know about this and it need to be fixed, but for now we can't remove
> this, it is needed for people installing from git (with makefile).

Right, I knew it, sometimes I install helm from git too.

> There is no urgency, loading such a file is really fast.

OK. I don't worry about this too much.

**Comment by thierryvolpiatto** [comment]
Anyway checking if file have been loaded would require looping in load-history, which would be even more costly than just loading (again) the autoload file.
So I am closing this for now.
