### ISSUE TITLE
Helm doesn't suggest completion for following strings in `multi-prompt-key-value`

### ISSUE THREAD

**Issue by giordano** [emacs-helm/helm#1161]
`multi-prompt-key-value` is a function part of [`multi-prompt`](http://git.savannah.gnu.org/gitweb/?p=auctex.git;a=blob;f=multi-prompt.el) package shipped with AUCTeX.  It's similar to `completing-read-multiple`, on which it's based.

What to do to trigger the bug:
````lisp
(multi-prompt-key-value "Prompt: " '(("key" ("value1" "value2"))))
````

What I expect:
Helm completes `key`, then I insert `=` and Helm should suggests `value1` and `value2` for completion.

What I get:
Helm completes only `key`, but not `value1` and `value2`.

**Comment by thierryvolpiatto** [comment]
Mosè Giordano <notifications@github.com> writes:

> multi-prompt-key-value is a function part of multi-prompt package
> shipped with AUCTeX. It's similar to completing-read-multiple, on
> which it's based.

So why auctex is not using `completing-read-multiple' ?
I had many issues with auctex because it uses wrongly the completions
functions of emacs, namely `completing-read' and
`completing-read-multiple'.

>
> What to do to trigger the bug:
>
> (multi-prompt-key-value "Prompt: " '(("key" ("value1" "value2"))))

This is wrong, the table should be '(("key") ("value1") ("value2"))
so that 

(multi-prompt-key-value "Prompt: " '(("key") ("value1") ("value2")))

works with a "," as separator.

> What I expect:
> Helm completes key, then I insert = and Helm should suggests value1 and value2 for completion.

Why "=" ?  Is this separator specified somewhere ?

> What I get:
> Helm completes only key, but not value1 and value2.

Normal the table is wrong.

Here are the official tests for `completing-read-multiple' that helm
conform too:

(defun crm-init-test-environ ()
  "Set up some variables for testing."
  (interactive)
  (setq my-prompt "Prompt: ")
  (setq my-table
	'(("hi") ("there") ("man") ("may") ("mouth") ("ma")
	  ("a") ("ab") ("abc") ("abd") ("abf") ("zab") ("acb")
	  ("da") ("dab") ("dabc") ("dabd") ("dabf") ("dzab") ("dacb")
	  ("fda") ("fdab") ("fdabc") ("fdabd") ("fdabf") ("fdzab") ("fdacb")
	  ("gda") ("gdab") ("gdabc") ("gdabd") ("gdabf") ("gdzab") ("gdacb")
	  ))
  (setq my-separator ","))

(completing-read-multiple my-prompt my-table)
(completing-read-multiple my-prompt my-table nil t)
(completing-read-multiple my-prompt my-table nil "match")
(completing-read my-prompt my-table nil t)
(completing-read my-prompt my-table nil "match")

All these tests are working in helm.
So what you have is a bug in auctex IMO.

-- 
Thierry

https://emacs-helm.github.io/helm/
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by giordano** [comment]
2015-09-10 16:10 GMT+02:00 Thierry Volpiatto <notifications@github.com>:
> So why auctex is not using `completing-read-multiple' ?
> I had many issues with auctex because it uses wrongly the completions
> functions of emacs, namely `completing-read' and
> `completing-read-multiple'.

Because `completing-read-multiple` can't do what AUCTeX needs.  `multi-prompt-key-value` provides completion for something like

    key1=value1,key2=value2

Before the equal sign, only completion for `key1` and `key2` is provided, after equal sign completion for all possible values associated to the selected keys is provided.  That's way completion table is an alist.

> > (multi-prompt-key-value "Prompt: " '(("key" ("value1" "value2"))))
>
> This is wrong, the table should be '(("key") ("value1") ("value2"))
> so that
>
> (multi-prompt-key-value "Prompt: " '(("key") ("value1") ("value2")))
>
> works with a "," as separator.

See above, `multi-prompt-key-value` syntax I give you to reproduce the bug is correct in.

> > What I expect:
> > Helm completes key, then I insert = and Helm should suggests value1 and value2 for completion.
>
> Why "=" ? Is this separator specified somewhere ?

LaTeX uses a lot this kind of syntax, there is base package, [`keyval`](https://www.ctan.org/pkg/keyval), just for that.

> So what you have is a bug in auctex IMO.

Thank you.

**Comment by thierryvolpiatto** [comment]
Mosè Giordano <notifications@github.com> writes:

> Because completing-read-multiple can't do what AUCTeX
> needs. multi-prompt-key-value provides completion for something like
>
> key1=value1,key2=value2
>
> Before the equal sign, only completion for key1 and key2 is provided,
> after equal sign completion for all possible values associated to the
> selected keys is provided.  That's way completion table is an alist.

I guess auctex should use the completion-in-region mechanism to be
clean.

See how crm.el is completing.

Probably you should report to auctex, I can't do something actually
(apart a big ugly hack).

-- 
Thierry

https://emacs-helm.github.io/helm/
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by giordano** [comment]
> I guess auctex should use the completion-in-region mechanism to be clean.

AUCTeX supports GNU Emacs and XEmacs down to version 21, `completion-in-region` has been introduced in GNU Emacs 23.2.

If you don't feel like fixing it, feel free to close this issue.

**Comment by thierryvolpiatto** [comment]
Mosè Giordano <notifications@github.com> writes:

>     I guess auctex should use the completion-in-region mechanism to be clean.
>    
> AUCTeX supports GNU Emacs and XEmacs down to version 21, completion-in-region has been introduced in GNU Emacs 23.2.

Helm is not supporting these versions of emacs, auctex should evolve
and refactor its code to be in sync with at least emacs-24 feature.

> If you don't feel like fixing it, feel free to close this issue.

Yes, I can't fix this sorry.

-- 
Thierry

https://emacs-helm.github.io/helm/
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
What you can do is adding the commands using multi-prompt to `helm-completing-read-handlers-alist`.
