### ISSUE TITLE
how to set `helm-buffer-list` major mode column width

### ISSUE THREAD

**Issue by QiangF** [emacs-helm/helm#1177]
Hi everyone,
We can change the buffer name maximum width by set helm-buffer-max-length,  how do I change the mode name column width? 
Thank you!

**Comment by thierryvolpiatto** [comment]
There is no way to change this.

**Comment by QiangF** [comment]
Most major mode names are less than 10 characters, it is unecessary to assign 20 character for that.
I will left this open, maybe someone can find a way.

**Comment by michael-heerdegen** [comment]
We get a lot of requests like this.  I agree lt would be good if things would be more configurable.  And I think it would be nice if we would make C-] a bit more polished and let it toggle between different "views", instead of simply hiding any column but the last. Similar to `ibuffer-switch-format' in ibuffer  (Maybe we could even use the ibuffer machinery for our purpose without needing to complicate our code?) @thierryvolpiatto would you be open to PRs doing this?  I don't have the time ATM unfortunately.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> We get a lot of requests like this. I agree lt would be good if things
> would be more configurable. And I think it would be nice if we would
> make C-] a bit more polished and let it toggle between different
> "views",

No, I am sorry but I don't want to work hours on something unuseful
that few people will play with it and to finish never use it anymore,
and I don't speak of the bugs I will have to fix during the next months.
We don't have to be too smart for such simple things.
What we have is perfectly fine.

-- 
Thierry
https://emacs-helm.github.io/helm/
