### ISSUE TITLE
Improve fake cursor in header-line?

### ISSUE THREAD

**Issue by xuchunyang** [emacs-helm/helm#1198]
When `(setq helm-echo-input-in-header-line t)`, for the current cursor's face, it's better to make it transparent when cursor is on a char. 

And someone also wants to customize that face (see http://emacs.stackexchange.com/questions/17058/change-cursor-type-in-helm-header-line), for example, use the face of cursor with `(setq cursor-type 'bar)`.

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

> When (setq helm-echo-input-in-header-line t), for the current cursor's
> face, it's better to make it transparent when cursor is on a char.
>
> And someone also wants to customize that face (see
> http://emacs.stackexchange.com/questions/17058/change-cursor-type-in-helm-header-line),
> for example, use the face of cursor with (setq cursor-type 'bar).

I will look into this tomorrow, thanks.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by michael-heerdegen** [comment]
The problem is that when the cursor color and the default face foreground are of the same color (that is the case for emacs -Q; both are black), the character is hidden by the cursor.  The "real" cursor is shown by a C routine that only works for point in a buffer, so we can't use it.

I though that
```
(defface helm-header-line-cursor
  '((t :inherit cursor :inverse-video t)) "...")
```
could work, but then, the cursor color is applied to the text foreground, which is wrong.

So, the logical consequence would be to use something like
```
'face `((t :inverse-video t :foreground ,(face-background 'cursor))) header-line-format)
```
in `helm--set-header-line'.

For using
```
(setq cursor-type 'bar)
```
for the fake cursor: this will never work because this option is only valid for a real cursor.  Our fake cursor is only a painted speck on a string we display in the header-line.

**Comment by hatschipuh** [comment]
@michael-heerdegen 

> Our fake cursor is only a painted speck on a string we display in the header-line.

Sorry for my ignorance but would it be possible to paint the string like a bar then?

**Comment by michael-heerdegen** [comment]
@hatschipuh Yes, I think it's not possible.  All we can do is using face attributes or the variants of the display text property.  And with that, you can have a box or underline the character, but nothing that looks like a bar type cursor.

That's why I noted that the code drawing the bar for the cursor is in C and not reachable from Lisp.

**Comment by hatschipuh** [comment]
@michael-heerdegen OK, thanks.
