### ISSUE TITLE
Problems of M-< (`helm-beginning-of-buffer')  and M-> (`helm-end-of-buffer')

### ISSUE THREAD

**Issue by xuchunyang** [emacs-helm/helm#1215]
For example:

1. call `helm-M-x`
2. then type `M->`, the current selection is not visible
2. then type `M-<`, the current source's header name is not visible

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

> For example:
>
>  1. call helm-M-x
>  2. then type M->, the current selection is not visible
>  3. then type M-<, the current source's header name is not visible

I don't understand what the problem is, I see always the selection here
when I move to bottom or top of buffer and of course when you move to
bottom of a buffer the top of buffer is not visible (unless you have a
buffer smaller or equal with window size).

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by xuchunyang** [comment]
It is likely to be my configuration issue. I have many history candidates (100+) in `helm-M-x` and customize the layout of helm-buffer's window heavily. I can't reproduce with emacs-helm.sh. I will try to figure out what caused this issue.

Sorry for the bad bug report.

**Comment by xuchunyang** [comment]
I found this is caused by setting `scroll-conservatively` (default 0) to a very large number such as 1000 for [Smooth Scrolling](http://www.emacswiki.org/emacs/SmoothScrolling), now I change it to 100 then this issue is gone.
