### ISSUE TITLE
Ability to not match the current buffer?

### ISSUE THREAD

**Issue by ReneFroger** [emacs-helm/helm#1302]
Assume I have two files `foo.html` and `bar.html`. The file `bar.html` is being open as the current buffer.

Then I open `helm-for-files`. When I'm typing `.html`, then the file `bar.html`
is being highlighted above `foo.html` in current files from the directory/recentf. 

Would it be possible to tell Helm if there are more cadidates, do not highlight
the file thats being opened in the current buffer?

**Comment by thierryvolpiatto** [comment]
No, use buffer listing instead.

**Comment by ReneFroger** [comment]
You mean the buffer-source in Helm?

**Comment by thierryvolpiatto** [comment]
Yes.

**Comment by ReneFroger** [comment]
You don't understand my point. But it makes no sense to explain, because you're not really helpful/willing to discuss things in topics. It's a great project, but with a grumpy maintainer unfortunately.

**Comment by michael-heerdegen** [comment]
The problem is that lots of people here (I don't mean you, personally) ask question/ request stuff and expect Thierry to invest a large amount of his time, while they are not willing to invest a tiny bit of their own time to understand stuff themselves/ read the code/ think about whether their request makes sense.
I would soon get grumpy under such conditions, too.  And it's Christmas, also for Thierry.

He is not our slave, and working on all these requests is hard work.  If it's a great project, his work can't have been so bad all the time.

But yes, he obviously didn't understand your request.  I think I did.

Did you think about how your proposal would fit into the current sorting of files?  I think implementing that would also slow down the thing, for a gain that doesn't seem so super useful to me.

Anyway, helm-ff-sort-candidates is already quite complicated.  The sorting is based on helm-ff-score-candidate-for-pattern, but also takes other things into account.

You want want to experiment with this stuff.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> The problem is that lots of people here (I don't mean you, personally)
> ask question/ request stuff and expect Thierry to invest a large
> amount of his time, while they are not willing to invest a tiny bit of
> their own time to understand stuff themselves/ read the code/ think
> about whether their request makes sense.  I would soon get grumpy
> under such conditions, too. And it's Christmas, also for Thierry.
>
> He is not our slave, and working on all these requests is hard
> work. If it's a great project, his work can't have been so bad all the
> time.

Thanks Michael ;-).

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by thierryvolpiatto** [comment]
ReneFroger <notifications@github.com> writes:

> You don't understand my point.

Ask yourself why I don't understand (I think I understood though, but
found your request not reasonable) most of the time your requests.
Before throwing (yes throwing and Thierry will do the rest) 
something on this list try to think harder what are your needs and if
you can't achieve what you want with the tools we provide to you.

> But it makes no sense to explain, because you're not really
> helpful/willing to discuss things in topics. It's a great project, but
> with a grumpy maintainer unfortunately.

I have been kind with you many times because you were a helm beginner,
now more than one year later you still not reading documentation,
variables (what is a variable) and else, so please help yourself.

Thanks.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by thierryvolpiatto** [comment]
And BTW see as example how @joonro have asked and argumented his request in #1301.
When you will be able to argument like this maybe I will be more helpful.

**Comment by ReneFroger** [comment]
@michael-heerdegen you made your point very clearly, thanks for that. I was already prepared to explain more in detail if the question was unclear enough. But the reaction of Thierry and suddenly closing my issues, turned me off and causes my reaction.

Sorry for that. I will study the code of Helm further, and yes, I follow all the issues here in order to learn something from it.
