### ISSUE TITLE
helm-eval-expression(-with-eldoc) does not run eval-expression hooks

### ISSUE THREAD

**Issue by hydandata** [emacs-helm/helm#1307]
Namely, `eval-expression-minibuffer-setup-hook` is not run, so if say you want to have paredit enabled you have to use something as ugly as this:

```elisp
(defun conditionally-enable-paredit-mode ()
  (if (eq this-command 'helm-eval-expression-with-eldoc)
      (enable-paredit-mode)))

(add-hook 'minibuffer-setup-hook 'conditionally-enable-paredit-mode)
```
Would be great if it just ran a hook.

**Comment by thierryvolpiatto** [comment]
David Chkhikvadze <notifications@github.com> writes:

> Namely, eval-expression-minibuffer-setup-hook is not run,

Because helm-eval-expression is just not eval-expression, it is
something else.

> so if say you want to have paredit enabled you have to use something
> as ugly as this:
>
> (defun conditionally-enable-paredit-mode ()
>   (if (eq this-command 'helm-eval-expression-with-eldoc)
>       (enable-paredit-mode)))
>
> (add-hook 'minibuffer-setup-hook 'conditionally-enable-paredit-mode)
>
> Would be great if it just ran a hook

No, I can't make a minibuffer hook just for this, try to tweak
helm-minibuffer-set-up-hook with perhaps a local variable you enabled in
helm-buffer just for helm eval or something like this.

-- 
Thierry
https://emacs-helm.github.io/helm/
