### ISSUE TITLE
Custom directory expansion

### ISSUE THREAD

**Issue by issue-dispenser** [emacs-helm/helm#1336]
Is there any chance of custom directory expansion similar to the expansion for "~/" and "/" in `helm-find-files`? It'd be great if I could do something like

```elisp
(add-to-list 'helm-ff-completions '(":EX:" . "/some/example/directory/"))
```
in my init.el, which would then expand a trailing ":EX:/" to "/some/example/directory/".

It'd make travelling around a large file system more enjoyable.

**Comment by thierryvolpiatto** [comment]
issue-dispenser <notifications@github.com> writes:

> Is there any chance of custom file name expansion similar to the expansion for "~/" and "/" in helm-find-files? It'd be great if I could do something like
>
> (add-to-list 'helm-ff-completions '(":EX:"  "/some/example/directory/"))
>
> which would expand a trailing ":EX:/" to "/some/example/directory/"

IIRC this have been already requested and fixed by using an environment
variable for such directory, don't remember the details though, will
look into this ASAP (You can search in issue tracker, it is there).


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Here how to use it:

1) Eval ```(setenv "EX" "/home/you/work/github/helm")```
(Notice that the path doesn't end with "/")
2) From anywhere in `helm-find-files` add "$EX/" at end of pattern.
e.g /usr/local/sbin/$EX/ will bring you straight to EX.

Note also that instead of using this you can bookmark at any moment your directories with C-x r m and retrieve them with C-x r b.
Also the history of directories is available from M-p, and to finish the file history is available from C-c h.

**Comment by issue-dispenser** [comment]
Thanks! Seems to work great. I haven't used bookmarks yet, but I'll look into them later.

Should this be (is it?) documented somewhere? I can see it being very handy.

**Comment by thierryvolpiatto** [comment]
issue-dispenser <notifications@github.com> writes:

> Should this be (is it?) documented somewhere? I can see it being very handy.

It is documented brievly in C-h m from helm-find-files.

-- 
Thierry

**Comment by issue-dispenser** [comment]
I see, thanks.
