### ISSUE TITLE
helm-recentf-source can't find the recentf-file when the location is changed.

### ISSUE THREAD

**Issue by ReneFroger** [emacs-helm/helm#1351]
My default directory is set with the following:  

    (setq user-emacs-directory "~/home/ReneFroger/"
           default-directory "~/home/ReneFroger/")
           
I noticed Emacs saves the recent files that I have visited in the file `recentf`, which will be stored in the `home/ReneFroger/` path. I would like to change the location of `recentf`.

So I added the following:

    (setq recentf-save-file (expand-file-name "recentf" "~/Emacs/.emacs.d/Linux")))

When restarting Emacs, I notice the recented files are saved correctly in the `recentf` file inside `~/Emacs/.emacs.d/Linux\recentf` file. But when I call `helm-for-files` with `helm-source-recentf` included, it doesn't show any files from `recentf`. The source is empty. 

When I remove the 

    (setq recentf-save-file (expand-file-name "recentf" "~/Emacs/.emacs.d/Linux")))

Then the `helm-source-recent` is able to show a list of recent files.

**Comment by thierryvolpiatto** [comment]
ReneFroger <notifications@github.com> writes:

> My default directory is set with the following:
>
> (setq user-emacs-directory "~/home/ReneFroger/"
>        default-directory "~/home/ReneFroger/")
>
> I noticed Emacs saves the recent files that I have visited in the file
> recentf, which will be stored in the home/ReneFroger/ path
> I would like to change the location of recentf
>
> So I added the following:
>
> (setq recentf-save-file (expand-file-name "recentf" "~/Emacs/emacsd/Linux")))
>
> When restarting Emacs, I notice the recented files are saved correctly
> in the recentf file inside ~/Emacs/emacsd/Linux\recentf file But when
> I call helm-for-files with helm-source-recentf included, it doesn't
> show any files from recentf The source is empty

At this time, I guess that if you eval `recentf-save-file` its value is
still "~/.emacs.d/recentf" isn't it ?

If yes, you should ensure your settings take effect after recentf is
loaded, for this you have to use `recentf-mode-hook` or
`with-eval-after-load`.
You can use also the customize interface to set your variable instead of
`setq` and finally if you use `use-package` add your setting in :config
slot.

This is a common emacs configuration problem, not specific to helm.

-- 
Thierry

**Comment by syohex** [comment]
@ReneFroger You should use `custom-set-variables` instead of `setq` if you set it after loading recentf.el. It has [`:set` attribute](https://github.com/emacs-mirror/emacs/blob/emacs-24.5/lisp/recentf.el#L72-L83) for re-loading recentf list(In this case. you need to enable `recent-mode` before setting value). If you use `custom-set-variables` then `:set` callback is called, but if you use `setq`, it is not called.

**Comment by thierryvolpiatto** [comment]
Syohei YOSHIDA <notifications@github.com> writes:

> @ReneFroger You should use custom-set-variables instead of setq if you
> set it after loading recentf.el. It has :set attribute for re-loading
> recentf list(In this case. you need to enable recent-mode before
> setting value). If you use custom-set-variables then :set callback is
> called, but if you use setq, it is not called.


As a side note, many people are reluctant to use the customize interface
because customize write in their init file, which is annoying,
it is no more a problem if you set `custom-file` to a different file 
(e.g ".emacs-custom.el"), this way you can safely use the customize interface.


-- 
Thierry

**Comment by ReneFroger** [comment]
Sorry for bothering you both. Your suggestions are appreciated. I solved it as follow:

    (recentf-mode 1)

    (setq recentf-save-file (expand-file-name "recentf"
    "~/Emacs/.emacs.d/Linux")))

    (recentf-load-list)

On the suggestion of @syohex after figuring it out. 
Since this is not related to Helm at all, I close this issue. Thanks for the suggestions by the way!

**Comment by ReneFroger** [comment]
Sorry for bothering you both. Your suggestions are appreciated. With using customize-option it gives me not the desired behaviour. I checked my `custom-file`, and the new location is set there. But I didn't see my recentf lists. 
I solved it in the another way as follow:

    (recentf-mode 1)

    (setq recentf-save-file (expand-file-name "recentf"
    "~/Emacs/.emacs.d/Linux")))

    (recentf-load-list)

On the suggestion of @syohex after figuring it out. 
Since this is not related to Helm at all, I close this issue. Thanks for the suggestions by the way!
