### ISSUE TITLE
emacs-helm.sh: Cannot open load file: no such file or directory, helm

### ISSUE THREAD

**Issue by vibrys** [emacs-helm/helm#1353]
Hallo Helm Team.

I encounter the message from subject when trying to run ./emacs-helm.sh from my elpa helm directory.
IMHO: the problem is caused by missing path to helm-core elpa repo within /tmp/helm-cfg.el.

I'm assuming that emacs-helm.sh is still prefered way to run minimal helm configuration. If I'm wrong please let me know.

Thank You for helm, it looks like it is the way to go for emacs.

best regards.

**Comment by thierryvolpiatto** [comment]
vibrys <notifications@github.com> writes:

> Hallo Helm Team
>
> I encounter the message from subject when trying to run /emacs-helmsh
> from my elpa helm directory IMHO: the problem is caused by missing
> path to helm-core elpa repo within /tmp/helm-cfgel

Don't you have an old emacs-helm.sh ?
I have fixed this bug some months ago, it is no more reproductible here
since long time now.

You should see in your emacs-helm.sh a call to `package-initialize`,
which is in charge to setup load paths.

To ensure you run the good one, don't forget the "./" when calling
emacs-helm.sh from your helm directory (assuming you are up to date).

> I'm assuming that emacs-helmsh is still prefered way to run minimal
> helm configuration If I'm wrong please let me know

No you are right, it is the best way to run a minimal helm.

> Thank You for helm, it looks like it is the way to go for emacs

Thanks.

-- 
Thierry

**Comment by vibrys** [comment]
I know why.

My .emacs points elpa repo with `package-user-dir', which is away from .emacs.d directory, but it seems that emacs-helm.sh requires elpa repo be on standard place.

after moving elpa to .emacs.d, ./emacs-helm.sh does the job.

Thierry,
thank You for Your help.

best regards.

**Comment by vibrys** [comment]
just for the sake of completeness,
I've used helm-20160121.2157 during the experiments.

best regards

**Comment by thierryvolpiatto** [comment]
Shoud work now even with a elpa directory located anywhere.

**Comment by vibrys** [comment]
Indeed, it works now.

thank You
