### ISSUE TITLE
stuck when tramp connection gets lost

### ISSUE THREAD

**Issue by abred** [emacs-helm/helm#1398]
Hello,

situation:
I'm editing files via ssh/tramp. The connection gets lost (for some reason). Sometimes tramp recovers, sometimes not. However, I can't do M-x tramp-cleanup-all-connections because as soon as I press M-x (aka helm-M-x) a request is sent do the remote server (which is currently unavailable) and emacs freezes.

output of debug/tramp buffer (tramp-verbose 8):
19:20:18.872941 tramp-get-file-property (8) # /home/user/folder/ file-exists-p t
(Also, when the connection is alive and I do M-x, I get one of these lines for every keystroke, if the current buffer is a remote one)

Same with helm-mini (helm-buffer-skip-remote-checking is t).

**Comment by thierryvolpiatto** [comment]
Not reproductible here, please start with ./emacs-helm.sh.

**Comment by abred** [comment]
ok, I narrowed it down.
The problem seems to lie in the interaction of helm and flycheck.
When global-flycheck-mode is t, each time a buffer is opened there is a check if flycheck-mode ought to be enabled. When I press M-x, a new buffer is created and the check is executed. The check fails if one of several test fails: certain major modes, ephemeral buffers, encrypted buffers, remote buffers. As far as I understand it, the "helm M-x" buffer should be an ephemeral buffer. However the convention seems to be that ephemeral buffers start with a space. That's not the case for all the helm-buffers. So the check succeeds and flycheck goes on to to its thing which causes my troubles.
An alternative solution would be to tell flycheck to ignore buffers starting with a * (or *helm).
 #1403

**Comment by thierryvolpiatto** [comment]
abred <notifications@github.com> writes:

> ok, I narrowed it down.

Great, thanks.

> The problem seems to lie in the interaction of helm and flycheck.
> When global-flycheck-mode is t, each time a buffer is opened there is
> a check if flycheck-mode ought to be enabled. When I press M-x, a new
> buffer is created and the check is executed. The check fails if one of
> several test fails: certain major modes, ephemeral buffers, encrypted
> buffers, remote buffers. As far as I understand it, the "helm M-x"
> buffer should be an ephemeral buffer.

Agreed, we already do this for the helm-candidates-buffer's.

> However the convention seems to be that ephemeral buffers start with a
> space. That's not the case for all the helm-buffers. So the check
> succeeds and flycheck goes on to to its thing which causes my
> troubles.

Good to know, thanks for explanation about flycheck.

> An alternative solution would be to tell flycheck to ignore buffers
> starting with a * (or *helm).  #1403

Thanks for your PR #1403, but I think it is better to always add the
space to helm-buffer if not already done, I have commited a change doing
this.

Thanks.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Thierry Volpiatto <thierry.volpiatto@gmail.com> writes:

> Thanks for your PR #1403, but I think it is better to always add the
> space to helm-buffer if not already done, I have commited a change doing
> this.

I have reverted this change because it cause problems to have the
helm-buffer ephemeral (we sometimes loose it on restart, and we loose in
some places text properties e.g elisp-packages).
I will reconsider making helm-buffer ephemeral but it needs more work.
Did you try disabling/reenabling flycheck with helm hooks ?
Also, perhaps flycheck have a variable to ignore helm buffers ? (it
should if not).

-- 
Thierry

**Comment by lunaryorn** [comment]
What major mode does helm use for its buffers?

**Comment by lunaryorn** [comment]
Besides, marking Helm's buffers as ephemeral is conceptually wrong:  Helm's buffers are not ephemeral, simply because the user is actually expected to interact with them.

**Comment by lunaryorn** [comment]
And some little background on Flycheck:  It does ignore all special buffers, by checking the `mode-class` of the current major mode for whether it's `special`.  I think that Helm should set that for its major modes.

**Comment by thierryvolpiatto** [comment]
Sebastian Wiesner <notifications@github.com> writes:

> And some little background on Flycheck: It does ignore all special
> buffers, by checking the mode-class of the current major mode for
> whether it's special.  I think that Helm should set that for its major
> modes.

If you ignore special-mode buffers, I don't see why you are not ignoring
fundamental-mode buffers, what the purpose of flycheck in those buffers ?
Even better would be for flycheck to allow users customizing which
major-mode/buffers to ignore.

-- 
Thierry

**Comment by lunaryorn** [comment]
> Even better would be for flycheck to allow users customizing which major-mode/buffers to ignore.

You can, see `flycheck-global-modes`, but that's not what we're talking about.

> If you ignore special-mode buffers, I don't see why you are not ignoring fundamental-mode buffers, what the purpose of flycheck in those buffers?

There's none; we simply never encountered fundamental-mode before.  I'm not aware of any library that actually uses fundamental-mode for anything—not even Emacs itself does as far as I know—and I'm surprised to see Helm do so.  

In my opinion that's not a good idea; I think you should always define specialized modes for buffers that serve a particular purpose, and I was under the impression that its use for buffers is discouraged in favour of defining custom modes.  But YMMV may wary, of course.

And to return the question:  Why doesn't Helm define it's own major mode?  The absence of a real Helm major mode leaves other libraries with no other choice than to inspect buffer name, and that's inherently more fragile than checking major mode symbols because names can change whereas symbols can not.

**Comment by thierryvolpiatto** [comment]
Sebastian Wiesner <notifications@github.com> writes:

> And to return the question: Why doesn't Helm define it's own major
> mode? The absence of a real Helm major mode leaves other libraries
> with no other choice than to inspect buffer name, and that's
> inherently more fragile than checking major mode symbols because names
> can change whereas symbols can not.

Done.

-- 
Thierry

**Comment by lunaryorn** [comment]
@thierryvolpiatto Thank you very much :blush:

**Comment by lunaryorn** [comment]
I guess we can close this issue now, because with Flycheck ignoring fundamental-mode now and Helm defining its own mode Flycheck Mode should not become active for any Helm version anymore.

**Comment by abred** [comment]
thanks to you both, it's fixed

**Comment by thierryvolpiatto** [comment]
Sebastian Wiesner <notifications@github.com> writes:

> @thierryvolpiatto Thank you very much :bl

Thanks for helping on this.

-- 
Thierry

**Comment by robohyun66** [comment]
Sorry if this has been answered, but I still want to check.
"Situation:
I'm editing files via ssh/tramp. The connection gets lost (for some reason). Sometimes tramp recovers, sometimes not. However, I can't do M-x tramp-cleanup-all-connections because as soon as I press M-x (aka helm-M-x) a request is sent do the remote server (which is currently unavailable) and emacs freezes."

I have this exact issue. What is the proposed solution or fix that has been made?

**Comment by thierryvolpiatto** [comment]
Can't reproduce, please check from a clean Emacs with `emacs-helm.sh`.
