### ISSUE TITLE
Can't keybinding with helm-do-grep

### ISSUE THREAD

**Issue by gentlegy** [emacs-helm/helm#1408]
Hi,

I am newbie to helm. I want to achieve a function that binding helm-do-grep* to some key (e.g. C-l) to fast find all files which match a pattern under current directory recursively. I search online and find a few solutions include:
1) blinding key to helm-do-grep-1, which doesn't exist in latest version
2) (setq helm-grep-default-command "grep -a -d recurse -n -e %p %f"), which change the default behavior, but I still want the flexibility to choose recursively finding or not.

It seems like the only command left in latest version is: helm-grep-do-git-grep, which only search for git repos. I also check wiki page, and it looks like the only way to use grep in helm (I don't want M-x grep) is C-x C-f then <tab> and then choose action "Grep File(s) `C-s, C-u Recurse'" with helm-grep-default-command modified above for recursively searching. Am I missing something? And what is the best way to use grep. BTW, I use MELPA to install latest helm.

Thanks so much for your help,
Yang

**Comment by thierryvolpiatto** [comment]
gentlegy <notifications@github.com> writes:

> Hi,
>
> I am newbie to helm. I want to achieve a function that binding helm-do-grep* to some key (e.g. C-l) to fast find all files which match a pattern under current
> directory recursively. I search online and find a few solutions include:
> 1) blinding key to helm-do-grep-1, which doesn't exist in latest
> version

helm-do-grep-1 is not an interactive command and can't be bounded to a
key.

helm-do-grep have been removed yes because it was doing exactly the same
than helm-find-files+C-s (without the power of helm-find-files on first
step).

> 
> 2) (setq helm-grep-default-command "grep -a -d recurse -n -e %p %f"),
> which change the default behavior, but I still want the flexibility to
> choose recursively finding or not.

You have two variables to setup though the default settings should fit
your needs.

helm-grep-default-command and helm-grep-default-recurse-command.

> It seems like the only command left in latest version is:
> helm-grep-do-git-grep, which only search for git repos.

Yes and also helm-grep-do-ag which grep recursively default-directory
even when not under git control.

> I also check wiki page, and it looks like the only way to use grep in
> helm (I don't want M-x grep) is C-x C-f then and then choose action
> "Grep File(s) `C-s, C-u Recurse'" with helm-grep-default-command
> modified above for recursively searching.

No as said above you need helm-grep-default-command and
helm-grep-default-recurse-command.

It work out of the box with default setting:

M-x helm-find-files (bind it to C-x C-f) and then C-u C-s.

> Am I missing something? And what is the best way to use grep. BTW, I
> use MELPA to install latest helm.

I personally use rarely recursive grep now I have helm-do-grep-ag and
helm-grep-do-git-grep.

for grep I use ack-grep as backend for helm from helm-find-files.

See my config file for helm here:
https://github.com/thierryvolpiatto/emacs-tv-config/blob/master/init-helm-thierry.el

Some people complained there is no recurse grep from default-directory
(directly without prompting for files), the answer is that it would do
the same than helm ag but ten times slowly.

Also helm ag is usable with pt (platinium searcher) as backend for
windows user whereas grep is working with only one version on windows
and is slow or not working at all.

-- 
Thierry

**Comment by gentlegy** [comment]
Hi Thierry,

Thanks so much for your fast response and guideline here. It is really helpful and I really appreciate it. So your current usage is that use helm ag to speed up "large and complex" search and use "M-x helm-find-files (bind it to C-x C-f) and then C-u C-s" to do regular search. That really make sense. I will close this myself. Thank you to offer such a great library.

Best,
Yang
