### ISSUE TITLE
Feature request: History for helm-ucs

### ISSUE THREAD

**Issue by tmalsburg** [emacs-helm/helm#1428]
It would be useful to have a history of recently selected Unicode characters at the top, similar to the Emacs command history in `helm-M-x`.

This could actually be useful in a lot of helm sources.  Would it make sense to make this a helm feature that can be switched on when creating a source?

**Comment by thierryvolpiatto** [comment]
Titus von der Malsburg <notifications@github.com> writes:

> It would be useful to have a history of recently selected Unicode
> characters at the top, similar to the Emacs command history in
> helm-M-x.

I don't think adding the ucs characters choosen themself to some history
would be helpful because you won't be able to match them once your
history become larger.
However storing the input you type in minibuffer to get those character
would be better, they would be accessible by cycling with M-p, the only
thing needed is to add a :history slot to the helm call with a valid
symbol.

> This could actually be useful in a lot of helm sources. Would it make
> sense to make this a helm feature that can be switched on when
> creating a source?

No, as you see above there is too many different cases for history.
helm-comp-read is providing a slot to build an history source, but it is
up to you to provide a way to save your history.
Anyway it is not to hard to write a helm call doing this:

```elisp
(defvar helm/test-hist nil)
(let ((hook (lambda ()
              (helm-aif (helm-get-selection)
                  (progn
                    (setq helm/test-hist (delete it helm/test-hist))
                    (push it helm/test-hist))))))
  (unwind-protect
       (progn
         (add-hook 'helm-after-action-hook hook)
         (helm :sources `(,(helm-build-sync-source
                            "test hist"
                            :candidates helm/test-hist)
                           ,(helm-build-sync-source
                             "test"
                             :candidates '(a b c d e f g h)))
               :buffer "*helm test*"))
    (remove-hook 'helm-after-action-hook hook)))
```
-- 
Thierry

**Comment by thierryvolpiatto** [comment]
```elisp
(defvar helm/test-hist nil)
(let ((hook (lambda ()
              (helm-aif (helm-get-selection)
                  (progn
                    (setq helm/test-hist (delete it helm/test-hist))
                    (push it helm/test-hist))))))
  (unwind-protect
       (progn
         (add-hook 'helm-after-action-hook hook)
         (helm :sources `(,(helm-build-sync-source
                            "test hist"
                            :candidates helm/test-hist)
                           ,(helm-build-sync-source
                             "test"
                             :candidates '(a b c d e f g h)))
               :buffer "*helm test*"))
    (remove-hook 'helm-after-action-hook hook)))
```
