### ISSUE TITLE
feature request: wildcards in helm-find-files

### ISSUE THREAD

**Issue by magnetophon** [emacs-helm/helm#1461]
It would be nice if you could do for example `helm-find-files ~/*.txt`

**Comment by thierryvolpiatto** [comment]
Bart Brouns <notifications@github.com> writes:

> It would be nice if you could do for example helm-find-files ~/*.txt

helm-find-files is a file browser, so it will never show the "*.txt"
files only with such a pattern, however you can execute an action on such
wildcards, e.g delete, copy, grep etc... Recursives wildcards are also
supported (bash shopt globstar), see C-h m for more infos.

-- 
Thierry

**Comment by magnetophon** [comment]
Sorry, I don't think I understand what you mean.

**Comment by xuchunyang** [comment]
Maybe you can goto `~/` and type `txt` or `.txt$` instead.

**Comment by magnetophon** [comment]
@xuchunyang Ah, thanks, that works.

**Comment by thierryvolpiatto** [comment]
Bart Brouns <notifications@github.com> writes:

> Sorry, I don't think I understand what you mean.

Try to look first at documentation with `C-h m` while you are in
helm-find-files session.

As @Chunyang said use this regexp pattern to see your files:
"/home/you/ txt$" (note the space before "txt").

Otherwise, you can copy, delete etc... your files by using wildcards:

From "/home/you/*.txt"

Use "M-C" to copy for example, this will copy all "*.txt" files to the
directory of your choice.

From "/home/you/**.txt"

The same action would copy all "*.txt" _recursively_

Hope that's clear.

-- 
Thierry
