### ISSUE TITLE
helm-imenu-fuzzy-match not worked?

### ISSUE THREAD

**Issue by zw963** [emacs-helm/helm#1486]
It seem like just not work when this variable set to t.

![recorded1262931873.gif](http://zw963.github.io/recorded1262931873.gif)

**Comment by thierryvolpiatto** [comment]
Billy <notifications@github.com> writes:

> It seem like just not work when this variable set to t.

It is not intended to be set (setq) but customized via M-x
customize-variable or customize-save/set-variable.

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub*


-- 
Thierry

**Comment by AssailantLF** [comment]
@thierryvolpiatto I think it could be better pointed out in the docs that this needs to be done with custom-set-variable, because I'm pretty new to Emacs and earlier today I spent a lot of time pulling my hair over why fuzzy matching wasn't working.

Also what is the exact difference between setq and custom-set-variable? Should I prefer using one over the other depending on different packages/scenarios?

**Comment by zw963** [comment]
Thanks, But `helm-buffers-fuzzy-matching`,  `helm-recentf-fuzzy-match` all worked with just
use setq?

```cl
(setq
 helm-buffers-fuzzy-matching t
 helm-completion-in-region-fuzzy-match t
 helm-recentf-fuzzy-match t
 )
```

**Comment by AssailantLF** [comment]
@zw963 That snippet doesn't work for me, but it does work when I use

    (custom-set-variables
      '(helm-buffers-fuzzy-matching t)
      '(helm-completion-in-region-fuzzy-match t)
      '(helm-recentf-fuzzy-match t))

**Comment by zw963** [comment]
> Also what is the exact difference between setq and custom-set-variable? Should I prefer using one over the other depending on different packages/scenarios?

I don't know the difference, i just to know `(custom-set-variable...)` is added by 
`M-x customize-variable` to emacs dotfiles, default is `$HOME/.emacs`.

but I settings all I needed settings manually though, all my package is installed from 
github manually too. For me, this is more clear and controllable, and if bug happen,
 I could found it quickly. because I know where and what insert into dotfiles.

**Comment by zw963** [comment]
```cl
(setq helm-imenu-fuzzy-match t)   ;; this line before (require 'helm-imenu) is worked for me
(require 'helm-imenu)
(global-set-key (kbd "C-c C-b") 'helm-imenu-in-all-buffers)
```

Maybe I should use `(custom-set-variables ...)` whenever need define a user config ...

Thanks @thierryvolpiatto

**Comment by thierryvolpiatto** [comment]
Austin W Smith <notifications@github.com> writes:

> @thierryvolpiatto I think it could be better pointed out in the docs that this needs to be done with custom-set-variable, because I'm pretty new to Emacs and earlier
> today I spent a lot of time pulling my hair over why fuzzy matching wasn't working.
>
> Also what is the exact difference between setq and
> custom-set-variable? Should I prefer using one over the other
> depending on different packages/scenarios?

Generally variables in emacs packages, helm or whatever are defined with
`defcustom`.
They may have for some reason in the definition of their defcustom a
:set function defined:

    (defcustom helm-imenu-fuzzy-match nil
      "Enable fuzzy matching in `helm-source-imenu'."
      :group 'helm-imenu
      :type  'boolean
      :set (lambda (var val)
             (set var val)
             (setq helm-source-imenu
                   (helm-make-source "Imenu" 'helm-imenu-source
                     :fuzzy-match helm-imenu-fuzzy-match))))


In such case if you redefine your variable with `setq` you change indeed
the value of the variable but you don't run the function the developer
have prepared specialy for this variable.
In our case `helm-imenu-fuzzy-match` we have to rebuild the source for
the variable to take effect.

Most people are reluctant to use the customize interface because it
garbage their init file with custom settings, me the first I don't like
this.
To avoid this you can use a special file to isolate your custom settings
from the one you write yourself in your init file (.emacs.el init.el or
whatever name), to achieve this use `custom-file`:

(setq custom-file "~/.emacs.d/.emacs-custom.el")
(load custom-file)

This is not enabled in emacs by default because it is not clear for
eveybody (even the emacs developers) where the custom settings should be
loaded.
Emacs developers claims it is unsafe to load custom-file on top of
init-file, (it is why by default custom settings are added at end of
.emacs). 
I do load this file on top of my .emacs since years without any problems,
custom is perfectly handling this.

So up to you to decide where to load this file.

HTH.

-- 
Thierry

**Comment by AssailantLF** [comment]
@thierryvolpiatto Thank you very much for the in-depth explanation and suggestions!

**Comment by zw963** [comment]
> (setq custom-file "~/.emacs.d/.emacs-custom.el") (load custom-file)

Cool, I use emacs four years now, don't know this special variable.
Thank very much.

**Comment by zw963** [comment]
> In such case if you redefine your variable with `setq` you change indeed the value of the variable but you don't run the function the developer have prepared specialy for this variable. In our case `helm-imenu-fuzzy-match` we have to rebuild the source for the variable to take effect.

But, following code worked well too. (not manually require any helm internal packages. (helm-files, helm-imenu ...), just `setq` needed variable and keybinding.

```cl
(require 'helm-config)
(setq helm-imenu-fuzzy-match t) 
;; avoid require helm internal package directly.
;; (require 'helm-imenu) 
(global-set-key (kbd "C-c C-b") 'helm-imenu-in-all-buffers)
```
This work well for me, why?

**Comment by thierryvolpiatto** [comment]
Billy <notifications@github.com> writes:

>     In such case if you redefine your variable with setq you change indeed the value of the variable but you don't run the function the developer have prepared
>     specialy for this variable. In our case helm-imenu-fuzzy-match we have to rebuild the source for the variable to take effect.
>    
> But, following code worked well too. (not manually require any helm internal packages. (helm-files, helm-imenu ...), just setq needed variable and keybinding.
>
> (require 'helm-config)
> (setq helm-imenu-fuzzy-match t) 
> ;; avoid require helm internal package directly.
> ;; (require 'helm-imenu) 
> (global-set-key (kbd "C-c C-b") 'helm-imenu-in-all-buffers)
>
> This work well for me, why?

This work well because the variable is set BEFORE loading helm-imenu
which use autoloads (so you don't have to require 'helm-imenu i.e keep
it commented or remove it).
As soon as you call M-x helm-imenu the helm-imenu.el file is loaded and
build the source using helm-imenu-fuzzy-match == t as value.

But now if you do:

    (setq helm-imenu-fuzzy-match nil)

you are stuck to fuzzy-match, if you want the change to take effect you
have to call customize on helm-imenu-fuzzy-match.

-- 
Thierry

**Comment by zw963** [comment]
Understood, Thanks @thierryvolpiatto
