### ISSUE TITLE
How to override any helm source customized keymap?

### ISSUE THREAD

**Issue by amosbird** [emacs-helm/helm#1510]
I'd like to make this keybinding configuration effective in every helm session. How can I achieve this? 

```elisp
  (with-eval-after-load 'helm
    (define-key helm-map (kbd "C-w") 'backward-kill-word)
    (define-key helm-map (kbd "C-u") '(lambda () (interactive) (kill-line 0)))
    (define-key helm-map (kbd "ESC") 'helm-keyboard-quit)
    (define-key helm-map (kbd "C-h") 'delete-backward-char))
```

**Comment by thierryvolpiatto** [comment]
Amos Bird <notifications@github.com> writes:

> I'd like to make this keybinding configuration effective in every helm
> session. How can I achieve this?

Generally with define-key, but your bindings are really bad, see below.

>   (with-eval-after-load 'helm
>     (define-key helm-map (kbd "C-w") 'backward-kill-word)

This one override helm-yank-text-at-point.

>     (define-key helm-map (kbd "C-u") '(lambda () (interactive)
>     (kill-line 0)))

This one is not recommended, it override universal-argument.

>     (define-key helm-map (kbd "ESC") 'helm-keyboard-quit)

Well you have C-g

>     (define-key helm-map (kbd "C-h") 'delete-backward-char))

Otherwise, again your binding use an important prefix reserved for help.

Generally for such questions, use the mailing list.

Thanks.

-- 
Thierry

**Comment by amosbird** [comment]
Thanks for the explaination. I've posted in the mailing list.
