### ISSUE TITLE
Functionality of helm-ls-git without git?

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [emacs-helm/helm#1544]
I love `helm-ls-git`. Is there any way to get the same functionality under paths without a git repo? Any helm command that serves the same purpose (even if slower?, e.g. based on `find`?)

**Comment by thierryvolpiatto** [comment]
Amelio Vazquez-Reina <notifications@github.com> writes:

> I love helm-ls-git. Is there any way to get the same functionality
> under paths without a git repo?

The starting point is helm-browse-project, if your directory is under
git, it will use helm-ls-git, under hg helm-ls-hg, under svn helm-ls-svn
(you have to install these packages) and finally if the directory is not
under VC, it will show the files under directory if you call
helm-browse-project with aprefix arg.


-- 
Thierry

**Comment by amelio-vazquez-reina** [comment]
Perfect. Thanks!

**Comment by amelio-vazquez-reina** [comment]
If the directory is not under VC, what prefix args does `helm-browse-project` take? (i.e. how would you use with one example?)  Sorry I read the help on the command but didn't know exactly how to use it :(

**Comment by thierryvolpiatto** [comment]
Amelio Vazquez-Reina <notifications@github.com> writes:

> If the directory is not under VC, what prefix args does
> helm-browse-project take?

Say we have "/home/you/foo/", a directory not under VC, and
`helm-browse-project` bound to `C-x C-d`.

From a buffer under this directory, you hit `C-x C-d`, you have a source
with only the opened buffers under this directory, quit.

Now hit `C-u C-x C-d` you have two sources, one listing the buffers and
one listing all files under this directory, quit.
All the files have been cached.

Now hit `C-x C-d`, because the files are cached helm display the two
sources, quit.

Now add or remove some files under this directory.
You want perhaps now to rebuild the cache, hit `C-u C-u C-x C-d `.

Of course all this is usable from helm-find-files.

Keep in mind that the recursion is made with elisp and is slow, so use
this with not too big directories.

For faster completion on directories (recursive) see the helm-find-files help. 

HTH.

-- 
Thierry
