### ISSUE TITLE
[serious bug]: Symbol's function definition is void: define-helm-type-attribute

### ISSUE THREAD

**Issue by zeltak** [emacs-helm/helm#1564]
Hi

after i helm update from Melpa (helm-20160713.947) i cant start emacs and get this:

```
Symbol's function definition is void: define-helm-type-attribute
```

any clue how to deal with this?

to be clear if i revert back to helm helm-20160707.305 this error goes away

best

Z

**Comment by thierryvolpiatto** [comment]
zeltak <notifications@github.com> writes:

> Hi
>
> after i helm update from Melpa (helm-20160713.947) i cant start emacs and get this:
>
> Symbol's function definition is void: define-helm-type-attribute
>
> any clue how to deal with this?

After each major changes, I have to face such problems.

1) You have library outside of helm that use define-helm-type-attribute
and helm-attributes which are deprecated since two years now.

Or

2) You made a bad install of helm and still have a old helm.el(c) file
somewhere, cleanup your elisp directories and reinstall helm.

In case 1) you should run ./emacs-helm.sh with no problems and see there
is no bug in helm.

This is a duplicate of #1561

-- 
Thierry

**Comment by zeltak** [comment]
ok i can confirm it was the package helm-grepint which after grepping (ironically.. :)) for define-helm-type-attribute came up with that package

once removed it was fixed

thx for the help

Z
