### ISSUE TITLE
'helm-filtered-bookmarks' opening delay caused by AutoFS automounting

### ISSUE THREAD

**Issue by caadar** [emacs-helm/helm#1571]
Problem: if some bookmark points to file in currently unmounted directory controlled by AutoFS (e.g. /auto/media), initial \*helm-filtered-bookmarks\* buffer opens each time with annoying ~3 sec delay needed to automount that directory.

Expected behavior: \*helm-filtered-bookmarks\* buffer opens instantly (as \*helm-bookmarks\* do), and automount starts only if it really needed.

OS: Gentoo GNU/Linux.

**Comment by thierryvolpiatto** [comment]
caadar <notifications@github.com> writes:

> Problem: if some bookmark points to file in currently unmounted
> directory controlled by AutoFS (e.g. /auto/media), initial
> *helm-filtered-bookmarks* buffer opens each time with annoying ~3 sec
> delay needed to that directory automount.

Can't reproduce.

1) Plug an usb key.
2) when mounted navigate to some directories and open it in dired.
3) From dired bookmark directory.
4) umount usb key.
5) open helm-filtered-bookmarks which popup instantly.

Note that in 2) bookmarking in helm-find-files instead of dired changes
nothing, same behavior, no delay.

Did I miss something ?
Can you reproduce from ./emacs-helm.sh ?

Here the two entries bookmarked just now for testing purpose:

(("readme.txt"
 (filename . "/media/thierry/SYSRESC/readme.txt")
 (front-context-string . "################")
 (rear-context-string)
 (position . 1))

("grub"
 (filename . "/media/thierry/SYSRESC/boot/grub/")
 (front-context-string . "efi.img\n  -rw-r-")
 (rear-context-string . " avril 26 09:59 ")
 (position . 241))

-- 
Thierry

**Comment by caadar** [comment]
This issue is not Helm fault endeed.

Problem reproducible with AutoFS and other auto (!) mounters possibly, not hand-operated mounts.

'file-directory-p' in 'helm-highlight-bookmark' function is culprit. It tries get access file/dir and trigger slow AutoFS by it, that causes visible delay.

Hopefully 'file-directory-p' used in conjunction with 'file-remote-p', so I set files/dirs controlled by AutoFS as remote ones:

```lisp
(setq autofs-key-regex "\/auto\/.*")  ; for '\auto' key in /etc/autofs/auto.master
(add-to-list 'file-name-handler-alist `(,autofs-key-regex . autofs-name-handler))

(defun autofs-name-handler (operation &rest args)
  (save-match-data
	(if (eq operation 'file-remote-p)
		"autofs"  ; non nil function return value
	  (autofs-name-run-real-handler operation args))))

(defun autofs-name-run-real-handler (operation args)
  (let ((inhibit-file-name-handlers (cons 'autofs-name-handler
										  (and (eq inhibit-file-name-operation operation)
											   inhibit-file-name-handlers)))
		(inhibit-file-name-operation operation))
    (apply operation args)))
```

Sorry for false alert.
