### ISSUE TITLE
`helm-locate-library` does not respect regexps

### ISSUE THREAD

**Issue by xiongtx** [emacs-helm/helm#1611]
## Expected behavior

Pattern matching with `helm-locate-library` should respect regexps, e.g. `^help` should match only library names that start with the word `help`.

Other Helm commands, like `helm-apropos`, respect regexps.

## Actual behavior from emacs-helm.sh if possible

Regexps are not respected.

## Steps to reproduce (recipe)

Run `helm-locate-library` and try to match using a regexp like `^help`.

## Backtraces if some (M-x toggle-debug-on-error)

N/A

## Describe versions of helm, emacs, operating system etc.

- Helm: 2.0
- Emacs: 25.1.1
- OS: Fedora 24

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> Expected behavior
>
> Pattern matching with helm-locate-library should respect regexps,
> e.g. ^help should match only library names that start with the word
> help.


First of all, as long as we are using fuzzy-matching here, this will not
work, regexp matching will start working as soon as multimatch kick in,
that is when you enter a space after the first pattern.

But even if disabling fuzzy here, the special "^" character will not
work because we are using a match-part function, explanation:

candidates in the search buffer (helm-candidate-buffer) are listed with
full path:

/home/you/helm-something.el

So what you are doing is re-search-forward "^helm" which is of course
not working and then helm is searching for match-part with same regexp.

So when disabling fuzzy, to make "^helm" working we need an additional
search fn like:

    (lambda (regexp)
      (re-search-forward
        (replace-regexp-in-string "\\`\\^" "" regexp) nil t))

Then, with this new fn, helm will jump the the first occurence of
"helm":

/home/you/helm-something.el
          ^

And then match-part will look at this candidate
("/home/you/helm-something.el")
and do (string-match "^helm" "helm-something.el")
which will now work.


So that is what we would have to do if fuzzy were not used here, but as
long as we are using it, we don't have to care of this.
If you want to customize fuzzy-matching in this command we should add a
variable of course to customize this but also the new search fn when
fuzzy is disabled.

--
Thierry

**Comment by xiongtx** [comment]
How is this different from how `helm-apropos` works? I haven't dug into the code enough to find out.

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> How is this different from how helm-apropos works?

helm-apropos is about symbols, helm-locate-library is about libraries
which are files.

You will have the same problem with helm-apropos if fuzzy is enabled.

More generally, when you are using helm-source-in-buffer and a
transformer that modify display part of candidate helm will search in
the `helm-candidate-buffer` and not the `helm-buffer`, but you can
specify a match-part fn that decide which part of candidate to match
(but not to search); It is done in two steps, basically:

    (re-search-forward regexp)
and then
    (string-match regexp in-this-line)

So to have what you want in helm-locate-library you have to:

    (re-search-forward "helm") ; "^helm" would match nothing here.
and then
    (string-match "^helm" (helm-basename candidate))

where candidate is e.g "/home/you/helm/helm-files.el" and pattern
"^helm".

I will try to give you some real examples to reproduce, not now I have not
the time.

-- 
Thierry

**Comment by xiongtx** [comment]
OK, so fuzzy matching prevents using regexps? If we turn fuzzy matching off, should `helm-locate-library` behave like `helm-apropos`?

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> OK, so fuzzy matching prevents using regexps?

Yes and no, fuzzy (anywhere in helm) apply to the first pattern, but as
soon you enter the second, multi-match regexp matching starts.

The special character "^" which match a beginning of line or string is a
special case though. 

> If we turn fuzzy matching off, should helm-locate-library behave like
> helm-apropos?

Yes, (when helm-apropos have fuzzy disabled) but by adding a new search
function tough.
I have commited a change allowing this.

Thanks.

--
Thierry
