### ISSUE TITLE
Very strange behaviour between helm and gpu

### ISSUE THREAD

**Issue by bassjacob** [emacs-helm/helm#1631]
## Expected behavior

Not to stutter
## Actual behavior from emacs-helm.sh if possible

The helm process stutters, the gpu seems to crash and every webkit program on the computer stops working.
## Steps to reproduce (recipe)

Rub a webkit program (chrome, slack, etc)
Run emacs with helm
Open helm-m-x
## Backtraces if some (M-x toggle-debug-on-error)

N/A
## Describe versions of helm, emacs, operating system etc.

Latest helm
Emacs 25.1
Archlinux

I'm sorry, I know this is super vague. I'm not really even sure how to begin debugging it.

**Comment by thierryvolpiatto** [comment]
Jacob Bass <notifications@github.com> writes:

> The helm process stutters, the gpu seems to crash and every webkit
> program on the computer stops working.

I hardly see how helm could trigger such a behavior, isn't the problem
elsewhere ?
Have a look at issue #1157, isn't it related ?

> Rub a webkit program (chrome, slack, etc)

Are you sure it is only webkit based programs ?

> Run emacs with helm

Did you start with ./emacs-helm.sh ?

> Open helm-m-x

And ?

> I'm sorry, I know this is super vague. I'm not really even sure how to
> begin debugging it.

Did you try to see with top what is taking all cpu usage ?

My guess is one of your external program to emacs is taking all cpu and
of course as soon as you run something costly in emacs it become slow
and unresponsive because it have no more ressources to run.

-- 
Thierry
