### ISSUE TITLE
not refresh candicate list when run helm-resume

### ISSUE THREAD

**Issue by zw963** [emacs-helm/helm#1633]
## Steps to reproduce (recipe)
1. Run `helm-git-grep-at-point`, we see a list occured.
2. switch to the first occured item, and delete it.
3. Run helm-resume, the deleted item is still in list. 
# expect behavior

When file buffer changed, we hope `helm-resume` could
refresh list as if invoke previous command again.

Thanks.

**Comment by thierryvolpiatto** [comment]
Billy.Zheng <notifications@github.com> writes:

> expect behavior
>
> When file buffer changed, we hope helm-resume could
> refresh list as if invoke previous command again.

No helm-resume should resume your last helm grep session, no more, if
you want to update hit `C-c C-u`.
Same when you save your helm grep buffer, after switching back to it, it
is not updated, hit `g` to update it.

The point of helm-resume is to NOT run a maybe costly update again,
otherwise running helm-resume WITH update makes no difference with
running the command again from scratch.

-- 
Thierry

**Comment by zw963** [comment]
Thanks.

>>  otherwise running helm-resume WITH update makes no difference with running the command again from scratch.

This is the point, it very different with run a command again when input lots of search keywords 
in minibuffer,  In fact, current-resume is only useful for grep like command.
for my use case, I run a helm command with a hotkey, and then always input some character to 
shrink the result.  in some case, it should be very comfortable if can refresh it.

Another point, the speed is never a problem for me,  unless in some very big `org-mode`
file with helm-imenu, It is slow than ido-imenu a lot.

**Comment by thierryvolpiatto** [comment]
Billy.Zheng <notifications@github.com> writes:

> This is the point, it very different with run a command again when
> input lots of search keywords in minibuffer,

Use in this case the history `M-p` which will bring up immediately your
last input.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
BTW, I have added the missing history var in helm ag.

-- 
Thierry

**Comment by zw963** [comment]
Thanks, I missing this hotkey !!
