### ISSUE TITLE
change behaviour of helm-execute-persistent-action for some commands that trigger helm ?

### ISSUE THREAD

**Issue by fredbert** [emacs-helm/helm#1666]
I've noticed, that some commands provide an action for its helm buffer and others don't. I want to be able to view a function's definition when I use find-function, without closing the current helm buffer.  How can I add this functionality ? Thanks.

**Comment by thierryvolpiatto** [comment]
fredbert <notifications@github.com> writes:

> I've noticed, that some commands provide an action for its helm buffer
> and others don't. For example, I want to be able to view a function's
> definition when I use find-function, without closing the current helm
> buffer.

`find-function` is not a native helm function, it is helmized by
helm-mode and should have the same behaviour as the emacs vanilla
command apart helm completion.

> How can I add this functionality ? Thanks.

You can't, well you can but will have to rewrite a whole function and
add it to `helm-completing-read-handlers-alist` which is worth an effort
since it is already implemented in native helm functions.

I suggest you use helm-apropos instead for all (find-function,
describe-function etc...).

--
Thierry

**Comment by fredbert** [comment]
Ok I will give it a try. Thanks for the help.
