### ISSUE TITLE
Can't select command with M-x if prefix of other command

### ISSUE THREAD

**Issue by mlsteele** [emacs-helm/helm#1676]
## Expected behavior
When running `helm-M-x`, typing "github-browse-file" as a filter pairs it down to two items.
- `github-browse-file-blame`
- `github-browse-file`

I have run `github-browse-file-blame` somewhat recently. It should be possible to run `github-browse-file`.

## Actual behavior from emacs-helm.sh if possible

It's impossible to run `github-browse-file` because the cursor is stuck in the "Emacs Command History" section. So no amount of `C-j` will get to `github-browse-file`.

![image](https://cloud.githubusercontent.com/assets/705646/22311661/87dcfa08-e322-11e6-997a-1f92f6ee627a.png)

## Steps to reproduce (recipe)

Run `helm-M-x` and select `github-browse-file-blame` so that it's in your history. Then run `helm-M-x` and try to find a way to run `github-browse-file`.

For that you'd need the `github-browse-file` package, but I'm sure this works with any two commands one of which prefixes the other.

## Describe versions of helm, emacs, operating system etc.

I'm using evil mode, btw.

OS: macOS Sierra 10.12.3 (16D32)

Emacs version: 24.5.1

Helm version: `helm-info-version` dies with "Wrong argument: stringp, nil". I have these elpa dirs.
```helm-20161212.2159
helm-ag-20161203.523
helm-core-20161213.1754
helm-descbinds-20160916.713
helm-descbinds-readme.txt
helm-projectile-20161213.2311
helm-spotify-20160905.1447
```

**Comment by thierryvolpiatto** [comment]
Miles Steele <notifications@github.com> writes:

> Expected behavior
>
> When running helm-M-x, typing "github-browse-file" as a filter pairs
> it down to two items.
>
>   * github-browse-file-blame
>   * github-browse-file
>
> I have run github-browse-file-blame somewhat recently. It should be
> possible to run github-browse-file.

My guess is that you have helm-move-to-line-cycle-in-source enabled, so
each time you are at last candidate of source C-n or <down> bring you
back to first candidate, you don't see it in your case because you have
only one candidate in M-x history.
So when this is enabled, use <right> or C-o.
Your best friend is C-h m in such situation where you should find infos
about this.

> Actual behavior from emacs-helm.sh if possible
>
> It's impossible to run github-browse-file because the cursor is stuck
> in the "Emacs Command History" section. So no amount of C-j will get
> to github-browse-file.

Are you sure you are using ./emacs-helm.sh ;-) ?

> I'm using evil mode, btw.

Which confirm you are not using ./emacs-helm.sh :-)

Should work with evil too, perhaps with other keybindings ?

> OS: macOS Sierra 10.12.3 (16D32)
>
> Emacs version: 24.5.1
>
> Helm version: helm-info-version dies with "Wrong argument: stringp,
> nil".

helm-info-version is not part of helm, I have not such command.

> I have these elpa dirs.

helm is missing, so where is helm-M-x coming from ?

> helm-ag-20161203.523
> helm-core-20161213.1754
> helm-descbinds-20160916.713
> helm-descbinds-readme.txt
> helm-projectile-20161213.2311
> helm-spotify-20160905.1447

--
Thierry

**Comment by mlsteele** [comment]
Thanks a bunch @thierryvolpiatto. `C-o` does the trick. That was really helpful despite my terrible description of what software I'm running. 😀
