### ISSUE TITLE
Add margin to helm header line

### ISSUE THREAD

**Issue by amosbird** [emacs-helm/helm#1690]
I'm using emacs inside terminal with https://github.com/blairdrummond/centering-window-mode . It uses  `(set-window-margins window left-to right-to)` to center windows. Here is what it looks like,

![](https://ptpb.pw/TsZ0.jpg)

I wonder if there is a way to add margin to helm headerline so it can be centered as well.

**Comment by thierryvolpiatto** [comment]
Amos Bird <notifications@github.com> writes:

> I wonder if there is a way to add margin to helm headerline so it can
> be centered as well.

Try to customize new variable `helm-header-line-space-before-prompt`,
should do the trick with 'left-margin as value, if you want some thing
more precise use an integer, e.g left-margin-width + 1.

--
Thierry

**Comment by amosbird** [comment]
Thanks. How can I directly update `helm` package from github instead of waiting melpa's rolling process?

**Comment by thierryvolpiatto** [comment]
Amos Bird <notifications@github.com> writes:

> Thanks. How can I directly update helm package from github instead of
> waiting melpa's rolling process?

1) Uninstall helm from melpa.
2) Clone the git-repo somewhere in your load-path.
4) cd to your helm directory and run make.

Otherwise if it's just to test the changes, just clone git-repo, load
manually helm.el (M-L) in HFF and set
`helm-header-line-space-before-prompt` to some value.

--
Thierry

**Comment by amosbird** [comment]
great. It works as expected.
