### ISSUE TITLE
Duplicate Minibuf menu item in menu bar

### ISSUE THREAD

**Issue by rdotdk** [emacs-helm/helm#1727]
## Expected behavior
Only one Minibuf menu item should be shown in menu bar

## Actual behavior from `emacs-helm.sh` if possible (See note at bottom)
There are two Minibuf menu items under Minibuf Menu in Menu bar

## Steps to reproduce (recipe)
./emacs-helm.sh
Enable menu bar mode
type M-x and click on Minibuf menu item in Menu bar using mouse
There are two Minibuf menu items under Minibuf Menu in Menu bar

## Describe versions of helm, emacs, operating system etc.
emacs version 26.0.50/ubuntu 16.04

## IMPORTANT NOTE:

If you are using a Unix or GNU-Linux system there is no excuses 
to not use `emac-helm.sh` to reproduce your bug in 99% of the cases.

**Comment by thierryvolpiatto** [comment]
Hmm, I see.

Not sure this is a helm bug, I suspect here an emacs bug of easy-menu, would be great to have a recipe starting from emacs -Q with some minibuffer code similar (basically) to what helm does.

**Comment by xiongtx** [comment]
Where is this `Minibuf` menu? I can't find it. Is it under `Tools`?

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> Where is this Minibuf menu? I can't find it. Is it under Tools?

You have such menu when minibuffer is active.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
I suspect a bug in menu-bar.el where a minibuf entry is made in two places using one or the other depending the context. Perhaps because the helm context (using minibuffer and completion at the same time) is not expected, the two entries are shown?
This is just a guess, I have no clues on this.
Anyway helm is not modifying this menu, so I think it is not a helm bug but an emacs bug.

**Comment by thierryvolpiatto** [comment]
If you are reallly annoyed by this perhaps submit a bug report to emacs.
Closing now.
Thanks.
