### ISSUE TITLE
`helm-add-action-to-source' to `helm-source-find-files' not working without using helm first

### ISSUE THREAD

**Issue by sheepduke** [emacs-helm/helm#1729]
## Expected behavior
When calling `helm-add-action-to-source` to `helm-source-find-files` without using helm first, it gives a error:
```
Debugger entered--Lisp error: (error "No buffer named *helm*")
```
It works when adding action to `helm-source-locate` but not `helm-source-find-files`.

This happens if I want to add some new actions to helm source inside my Emacs configuration file.
I suppose it is a bug related to helm-source-find-files.

## Actual behavior from `emacs-helm.sh` if possible (See note at bottom)
Same as described above.

## Steps to reproduce (recipe)
1. After Emacs booting, insert the following line into `\*scratch\*` buffer:
```
(helm-add-action-to-source "Attach to Email" #'mml-attach-file helm-source-find-files)
```

2. eval it.

3. The error is emitted by Emacs.

## Backtraces if some (M-x toggle-debug-on-error)
```
Debugger entered--Lisp error: (error "No buffer named *helm*")
  helm-get-current-source()
  helm-attr(action nil ignorefn)
  helm-add-action-to-source("Attach to Email" mml-attach-file nil)
  eval((helm-add-action-to-source "Attach to Email" (function mml-attach-file) helm-source-find-files) nil)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```

## Describe versions of helm, emacs, operating system etc.
```
GNU Emacs 25.2.1 (x86_64-pc-linux-gnu) of 2017-03-07
helm 20170327.1326 (installed from melpa)
Linux 4.9.14-gentoo 2017 x86_64 Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz GenuineIntel GNU/Linux
```

## IMPORTANT NOTE:

If you are using a Unix or GNU-Linux system there is no excuses 
to not use `emac-helm.sh` to reproduce your bug in 99% of the cases.

**Comment by xiongtx** [comment]
This is because [`helm-source-find-files`](https://github.com/emacs-helm/helm/blob/v2.5.4/helm-files.el#L527) is initially `nil`, while [`helm-source-locate`](https://github.com/emacs-helm/helm/blob/v2.5.4/helm-locate.el#L354) is initialized with a Helm source.

I'm not sure if it's reasonable to initialize `helm-source-find-files` as well; maybe not, for performance reasons? @thierryvolpiatto can give more insight into that.

**Comment by sheepduke** [comment]
@xiongtx Well, I understand this is related to the implementation of helm. However, I think there should be a way for user (let us say, me) to specify another action to some sources in the init file.

Seriously, adding action `mml-attach-file` really rocks.

**Comment by thierryvolpiatto** [comment]
Danny Yue <notifications@github.com> writes:

> @xiongtx Well, I understand this is related to the implementation of
> helm. However, I think there should be a way for user (let us say, me)
> to specify another action to some sources in the init file.

You have a user variable to configure helm-find-files and most sources
have one now, see `helm-find-files-actions`.
Otherwise when a source is not loaded `helm-add-action-to-source` is not
usable, read its docstring it is explained, probably this function
should be internal.
You can now configure sources not loaded with defmethod if they have
their own class, see:
https://github.com/emacs-helm/helm/wiki/FAQ#why-is-a-customizable-helm-source-nil
and my config file here:
https://github.com/thierryvolpiatto/emacs-tv-config/blob/master/init-helm-thierry.el#L300


> Seriously, adding action mml-attach-file really rocks.

Yes and it already exists in helm-find-files (C-c C-a), it is not
mml-attach-file which is called directly but gnus-attach-file which use
mml-attach-file IIRC.
It is a conditional action so you don't see it in menu action unless you
are in a message buffer, it is however accessible by key.

I will add an entry in help.

--
Thierry

**Comment by sheepduke** [comment]
On 2017-03-29 05:03, Thierry Volpiatto <notifications@github.com> wrote:
> Danny Yue <notifications@github.com> writes:
>
>> @xiongtx Well, I understand this is related to the implementation of
>> helm. However, I think there should be a way for user (let us say, me)
>> to specify another action to some sources in the init file.
>
> You have a user variable to configure helm-find-files and most sources
> have one now, see `helm-find-files-actions`.
> Otherwise when a source is not loaded `helm-add-action-to-source` is not
> usable, read its docstring it is explained, probably this function
> should be internal.
> You can now configure sources not loaded with defmethod if they have
> their own class, see:
> https://github.com/emacs-helm/helm/wiki/FAQ#why-is-a-customizable-helm-source-nil
> and my config file here:
> https://github.com/thierryvolpiatto/emacs-tv-config/blob/master/init-helm-thierry.el#L300
>
>
>> Seriously, adding action mml-attach-file really rocks.
>
> Yes and it already exists in helm-find-files (C-c C-a), it is not
> mml-attach-file which is called directly but gnus-attach-file which use
> mml-attach-file IIRC.
> It is a conditional action so you don't see it in menu action unless you
> are in a message buffer, it is however accessible by key.
>
> I will add an entry in help.
>
> --
> Thierry

Oops, I did not think of it. I thought it was the interface to
customize, because I have seen someone else doing this.

You are right. I see this:
```
SOURCE should be an existing helm source already loaded.
```

By the way your configuration does help. Thanks a lot.

I think this can be closed.

Danny

**Comment by sheepduke** [comment]
This is not a bug, but a feature ;-)
Adding actions can be done by defining methods, see URLs provided by @thierryvolpiatto
