### ISSUE TITLE
Move helm-browse-menubar to separate package?

### ISSUE THREAD

**Issue by alphapapa** [emacs-helm/helm#1740]
There's a [discussion](https://github.com/melpa/melpa/issues/2342#issuecomment-291906557) going on on MELPA about wiki-sourced packages and their security risks.  `helm-browse-menubar` uses `lacarte`, which is one of them.  Thankfully Helm does not depend on it, so it doesn't get automatically installed with Helm, but only if the user runs the command and approves the request to install it.  However, this is still making use of a wiki-sourced package directly in the main Helm package.

Would you be willing to split the lacarte/menu stuff into a separate package?  It would be nice to have anything using wiki-sourced dependencies in dedicated package.

Thanks.

**Comment by xiongtx** [comment]
`lacarte` is a "Drew Adams package"; doesn't the MELPA discussion indicate that his packages are handled specially?

**Comment by alphapapa** [comment]
Yes, but as I commented there, I don't feel like special-casing his packages is a good idea.  I don't think relying on any wiki's security is a good idea.  I would just like to compartmentalize the wiki-sourced packages to make it easy to keep anything that uses them off my system.  :)

**Comment by xiongtx** [comment]
:man_shrugging: If you don't use `helm-browse-menubar`, you won't download `lacarte`. And even if you do call it, it asks you to confirm installing it.

**Comment by alphapapa** [comment]
I understand that.  I still request that it be moved to a separate package.

**Comment by thierryvolpiatto** [comment]
alphapapa <notifications@github.com> writes:

> There's a discussion going on on MELPA about wiki-sourced packages and
> their security risks. helm-browse-menubar uses lacarte, which is one
> of them. Thankfully Helm does not depend on it, so it doesn't get
> automatically installed with Helm, but only if the user runs the
> command and approves the request to install it. However, this is still
> making use of a wiki-sourced package directly in the main Helm
> package.

Indeed, thus people are not aware of the emacswiki security issue and
even don't know where the package comes from.

> Would you be willing to split the lacarte/menu stuff into a separate
> package? It would be nice to have anything using wiki-sourced
> dependencies in dedicated package.

The separate package will suffer the same problem.
Perhaps moving it to emacs-helm, but removing the yes-or-no automatic
install, not adding it to MELPA, and strongly warn in README that the
dependency to install (manually by user this time) is unsafe, up to the
user to verify the code of package he install.

Can someone do this ?

1) Copy the code to a separate file, removing the yes-or-no MELPA
installation part (see commit and just revert).
2) Make a README file.
3) Add the package to emacs-helm.
4) Make a PR that just remove this code.

Otherwise I will do it next week.

Thanks.

--
Thierry

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> lacarte is a "Drew Adams package"; doesn't the MELPA discussion
> indicate that his packages are handled specially?

There is no guarantees that Drew's files are correctly protected on such
an unsafe place.

--
Thierry

**Comment by alphapapa** [comment]
Thank you Thierry!
