### ISSUE TITLE
problems with ffap

### ISSUE THREAD

**Issue by brotzeitmacher** [emacs-helm/helm#1768]
I updated helm recently and `ffap` isn't working anymore. Do you have an idea how to fix this ? Thanks.

## Backtrace

Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-name-as-directory(nil)
  helm-comp-read-get-candidates(ffap-read-file-or-url-internal nil nil nil)

**Comment by thierryvolpiatto** [comment]
brotzeitmacher <notifications@github.com> writes:

> I updated helm recently and ffap isn't working anymore. Do you have an
> idea how to fix this ?

(add-to-list 'helm-completing-read-handlers-alist 
             '(ffap . helm-completing-read-sync-default-handler))

I will add this as default tomorrow.

But really you should use `helm-find-files` instead of the ugly ffap functions
(ffap, find-file-at-point, etc...) their interactive implementation is terrible.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by brotzeitmacher** [comment]
I have already tried to avoid ffap, but I still use ls in shell mode frequently and in combination with avy it's also pretty fast. Thanks for the help.

**Comment by thierryvolpiatto** [comment]
Not sure to understand the relation with ls in shell-mode where you have helm completion...
