### ISSUE TITLE
`helm-ff-checksum` action should not be available for directories

### ISSUE THREAD

**Issue by xiongtx** [emacs-helm/helm#1769]
## Expected behavior

`helm-ff-checksum` action, found in the actions list of commands like `helm-find-files`, should not be available for directories.

## Actual behavior from `emacs-helm.sh` if possible (See note at bottom)

`helm-ff-checksum` is available for directories. Calling it signals an error:

```
error in process sentinel: Read error: Is a directory, <dir-name>
```

but not before prompting the user for the checksum algorithm, which is unnecessary work.

## Steps to reproduce (recipe)

1. Call `helm-find-files`
2. Move selection to directory
3. Call `helm-ff-checksum` (`<f4>`)

## Backtraces if some (M-x toggle-debug-on-error)

```
Debugger entered--Lisp error: (file-error "Read error" "Is a directory" "/home/txx/.emacs.d/elpa/helm-20170511.649")
  signal(file-error ("Read error" "Is a directory" "/home/txx/.emacs.d/elpa/helm-20170511.649"))
  async-handle-result(#[257 "\302!\210\303\304\300\301#\207" [sha256 "helm-20170511.649" kill-new message "Calculating %s checksum for `%s' done and copied to kill-ring"] 5 "\n\n(fn SUM)"] (async-signal (file-error "Read error" "Is a directory" "/home/txx/.emacs.d/elpa/helm-20170511.649")) #<buffer *emacs*>)
  async-when-done(#<process emacs> "finished\n")
```

## Describe versions of helm, emacs, operating system etc.

- Helm: `20170511.649`
- Emacs: `25.1.1`
- OS: `Fedora 24`

**Comment by thierryvolpiatto** [comment]
Done, thanks.

**Comment by xiongtx** [comment]
Here's a thought: optional actions should come last, not be injected into the middle.

If we have actions like:

```
<f1> A
<f2> B
<f3> C
```

It makes more sense to *append* an action like:

```
<f1> A
<f2> B
<f3> C
<f4> D
```

than inject it like:

```
<f1> A
<f2> B
<f3> D
<f4> C
```

because injecting an action shifts the keys for every subsequent action; this requires the user to remember that `C` is `<f4>` for files, for example, but `<f3>` for dirs.

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> Here's a thought: optional actions should come last, not be injected
> into the middle.

> because injecting an action shifts the keys for every subsequent
> action; this requires the user to remember that C is <f4> for files,
> for example, but <f3> for dirs.

This is a good reason to move optional actions at bottom but there is
also good reasons to move some actions on top... So, well I opted for
moving actions on top or nearly because generally these actions are
really what you need on this kind of candidate. Also this allow user to
discover a new action have been added, at bottom they don't see it.
But perhaps it is better moving all at bottom except the ones affecting
first action e.g

~/.emacs.d/emacs-config/.emacs.el! C-x C-f RET
and
~/.emacs.d/emacs-config/.emacs.el:754! C-x C-f RET

don't know for now...

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997
