### ISSUE TITLE
Allow marking in eshell completion

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#1784]
For instance when completing on files, it is often useful to insert more than one result at once.
```
ls <tab>
```
Then select, then confirm, and you end up with
```
ls foo bar baz ...
```

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> For instance when completing on files, it is often useful to insert more than one result at once.
>
> ls <tab>
>
> Then select, then confirm, and you end up with
>
> ls foo bar baz ...

I understand but this would too complicated to implement properly than
the benefit it would provide, thus it would be confusing.

The goal of completion in shells is just to provide completion when user
hit TAB, no more. 

What I could do is implement a variant of C-c C-i in helm-find-files
that would insert marked with a space instead of a newline.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by Ambrevar** [comment]
I can't see why this would be harder with tab completion than with `C-c C-i`.

Completion does not have to remain as limited as it is for conservative shells.
Tools like `fzf` can already empower bash, zsh and fish to multi-complete.
I'm not sure where you think this would be confusing, I've been using it for months (years?), I've never hit an ambiguity.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I can't see why this would be harder with tab completion than with C-c C-i.

Indeed easier than expected, have a try at eshell_insert_marked branch
and let me know if it fits your needs.

Thanks.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by Ambrevar** [comment]
Seems to be working well, thanks!

**Comment by thierryvolpiatto** [comment]
If you think it works as expected for you feel free to close.

Thanks.

**Comment by Ambrevar** [comment]
All good, thank you very much.
