### ISSUE TITLE
Difference between grep and occur

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#1791]
I was just wondering, what's the practical difference between `grep` and `occur`? (Or, say, between `M-g s` and `C-s` in `helm-mini`?)

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I was just wondering, what's the practical difference between grep and
> occur? (Or, say, between M-g s and C-s in helm-mini?)

Grep is faster, it is why I don't remove it from helm buffer-list, but I
personally don't use it from here, I use only helm-(m)occur.
Originally I added grep as action to buffer-list because I had not
already implemented helm-occur at the time, it was a way to search in
buffers, limited to buffers representing a file of course.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by Ambrevar** [comment]
Thanks.
