### ISSUE TITLE
helm-top: Allow marking

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#1794]
I think it would be nice to allow marking in `helm-top` so that we can kill several processes at once.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I think it would be nice to allow marking in helm-top so that we can
> kill several processes at once.

I didn't add this because killing process may lead to problems, so I
prefered letting people killing processes one by one with persistent
action (or not) to ensure they don't kill an important process marked by
error.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by Ambrevar** [comment]
Which problems?
How do you mark by error?

In the end, it's up to the user to use marks. If some think they'd go on a mark-frenzy, fine, don't use it. But I think it's nice to leave the option to those who are confident they can use marks properly :)

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> In the end, it's up to the user to use marks. If some think they'd go
> on a mark-frenzy, fine, don't use it. But I think it's nice to leave
> the option to those who are confident they can use marks properly :)

Nice to have a feedback on this, ok I will enable marks, it's easy to do.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by Ambrevar** [comment]
Thanks!
