### ISSUE TITLE
How I can disable specific command from helm auto completion?

### ISSUE THREAD

**Issue by ryukinix** [emacs-helm/helm#1813]
At example I have the command gdb disabled with (put 'gdb 'disabled t) for personal reasons. However the command still appears on autocomplete and annoys me. This is possible?

**Comment by thierryvolpiatto** [comment]
Manoel Machado <notifications@github.com> writes:

> At example I have the command gdb disabled with (put 'gdb 'disabled t)
> for personal reasons. However the command still appears on
> autocomplete and annoys me. This is possible?

No because your command (a symbol) is still present in obarray.
Note that this is more an emacs question that one relative to helm.
Anyway I think it is a bad idea trying to do that.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by ryukinix** [comment]
Thanks for clarification.
