### ISSUE TITLE
Have helm-org-heading-refile refile the marked items in org-mode agenda view

### ISSUE THREAD

**Issue by dinojr** [emacs-helm/helm#1830]
At the moment, helm-org-agenda-files-headings offer to refile entries in the agenda files but only one at a time. However, the agenda view has a bulk-action mode where several entries in the agenda view can be marked (with org-agenda-bulk-mark bound to "m"). It would be a nice improvement if helm-org-heading-refile could use this list of headings (when it exists) as a list of headings to refile to the current heading in the helm-session.

**Comment by alphapapa** [comment]
I think Helm doesn't need direct support for this, because it already supports it by being a completion method.  All you need to do is mark the entries and call the bulk refile action `B r`.  That should open a Helm buffer with headings to choose as a refile target, depending on your `org-refile` settings.  If it doesn't, you can enable it by using `helm-mode`.

**Comment by dinojr** [comment]
You're right. org-refile + helm is enough for that, but since
helm-org-agenda-files-heading offers to refile entries, it could as well
refile several at once.

**Comment by dinojr** [comment]
You're right. org-refile + helm is enough for that, but since
helm-org-agenda-files-heading offers to refile entries, it could as well
refile several at once.

**Comment by alphapapa** [comment]
You can do that already.  Mark the headings you want to refile, then select the target and use the refile action.

**Comment by thierryvolpiatto** [comment]
Marking with helm-mode generated sources is not possible AFAIK so I think @dinojr request is legitimate. What about detecting org marks in agenda buffer and use them instead of `helm-marked-candidates` in `helm-org--refile-heading-to` ?

Or write a new command similar to `helm-org--refile-heading-to` but specialized for agenda buffer and taking the list of org marked candidates instead of helm-marked-candidates ?

Another solution would be to pre mark all the org marked (when some) in helm-buffer at startup of `helm-org-in-buffer-headings` and preselect the first one ?

**Comment by alphapapa** [comment]
Sorry, I think either you don't understand me or I don't understand you.

This is already possible with Helm when Helm is the default completing-read function.

1.  Open agenda buffer.
2.  Mark entries with `m`.
3.  Press `B r` to bulk-refile.
4.  Select target heading with Helm.
5.  Press `RET`.
6.  Marked headings are refiled to the chosen heading.

I just tested this, it works.

**Comment by alphapapa** [comment]
> There is also a command called org-agenda-refile, don't know what it is doing.

That's what `B r` calls, through `org-agenda-bulk-action`.

Thanks.

**Comment by thierryvolpiatto** [comment]
alphapapa <notifications@github.com> writes:

>     There is also a command called org-agenda-refile, don't know what it is doing.
>    
> That's what B r calls, through org-agenda-bulk-action.

Ok, thanks.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997
