### ISSUE TITLE
dired-do-copy not work if destination is paste from a not expanded path

### ISSUE THREAD

**Issue by tangxinfa** [emacs-helm/helm#1840]
## Steps to reproduce (recipe)
1, open a dired buffer
2, move your cursor on a file
3, press "C" to do copy
4, in minibuffer it prompt "Copy xxx to: "
5, paste a path contains "~" char, such as: ~/Examples/
6, helm candidate list is empty, press "RET", nothing happen, copy failed

In step 5, if you input "~/Examples" by hand it will expand to "/home/yourname/Examples", and it works,
but it's not convenient to use, currently i use the following settings for bypass this problem:
     (setq dired-dwim-target t)

**Comment by thierryvolpiatto** [comment]
tangxinfa <notifications@github.com> writes:

> Steps to reproduce (recipe)
>
> 1, open a dired buffer
> 2, move your cursor on a file
> 3, press "C" to do copy
> 4, in minibuffer it prompt "Copy xxx to: "
> 5, paste a path contains "~" char, such as: ~/Examples/
> 6, helm candidate list is empty, press "RET", nothing happen, copy failed

I think you forget to mention an extra step between 4 and 5, that you
deleted minibuffer contents, right ?
If so it is fixed, otherwise, if you directly pasted "~/Examples/" after
the current path it was already working, i.e after step 3, your
minibuffer contains "/home/you/foo/" and you paste directly
"~/Examples/" after it, which save you the step of deleting minibuffer
contents (that I suppose you did).

Thanks.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by tangxinfa** [comment]
> I think you forget to mention an extra step between 4 and 5, that you deleted minibuffer contents, right ?
yes, i deleted minibuffer contents before paste "~/Examples/".

Very glade to hear this problem is fixed, thank you:)

**Comment by thierryvolpiatto** [comment]
tangxinfa <notifications@github.com> writes:

> yes, i deleted minibuffer contents before paste "~/Examples/".

So you don't need to delete minibuffer contents before pasting, you can
juste paste directly at end of "/home/you/foo/".

Closing now.

Thanks.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997
