### ISSUE TITLE
helm-comp-read-must-match-map overrides :keymap in helm-comp-read

### ISSUE THREAD

**Issue by fice-t** [emacs-helm/helm#1842]
## Expected behavior
`:keymap` argument overrides all other Helm keymaps. 

## Actual behavior from `emacs-helm.sh` if possible
`helm-comp-read-must-match-map` overrides the `:keymap` argument.

## Steps to reproduce (recipe)
```elisp
(defvar helm--test-map
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "RET") (lambda ()
                                  (interactive)
                                  (minibuffer-message " [Test]")))
    map))

(helm-comp-read "Test: " '(one two three) :must-match t :keymap helm--test-map)
```

While in the minibuffer, `C-h k RET` yields `helm-confirm-and-exit-minibuffer`, and not the anonymous procedure bound in `helm--test-map`.

It's uncommon to rebind `RET` here, but I believe it should still be allowed.

## Describe versions of helm, emacs, operating system etc.
Latest MELPA version, Emacs 26, and GNU/Linux.

**Comment by thierryvolpiatto** [comment]
fice-t <notifications@github.com> writes:

> Expected behavior
>
> :keymap argument overrides all other Helm keymaps.
>
> Actual behavior from emacs-helm.sh if possible
>
> helm-comp-read-must-match-map overrides the :keymap argument.
>
> Steps to reproduce (recipe)
>
> (defvar helm--test-map
>   (let ((map (make-sparse-keymap)))
>     (define-key map (kbd "RET") (lambda ()
>                                   (interactive)
>                                   (minibuffer-message " [Test]")))
>     map))
>
> (helm-comp-read "Test: " '(one two three) :must-match t :keymap helm--test-map)
>
> While in the minibuffer, C-h k RET yields helm-confirm-and-exit-minibuffer, and not the anonymous procedure bound in helm--test-map.
>
> It's uncommon to rebind RET here, but I believe it should still be
> allowed.

No, it should be allowed as long as you don't use :must-match, but if
you use :must-match it will override your keymap and that's the expected
behavior, otherwise you would break the must-match mechanism.

If you really want to use something different you can use the helm
framework and redefine a new completing-read, binding it to
completing-read-function but you will hit the same problem as soon as a
user want to use the require-match argument of completing-read.

So, no don't expect a change in helm along this.


-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment]
Closing this as really the expected behavior is to override the current map with the must-match map when must-match argument is provided.
