### ISSUE TITLE
helm-bookmark is not loaded automatically anymore

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#1847]
I saw that you've changed the way `helm-bookmark` is loaded.
I was wondering why.
Did you document this anywhere? Maybe I failed to see this.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I saw that you've changed the way helm-bookmark is loaded.

Yes, helm-bookmark among others.

I am actually modifying the way helm is loading, perhaps you noticed it
faster to load.

helm-bookmark is now loading:

1) By autoload when you call helm-bookmarks or helm-filtered-bookmarks

2) When calling helm-for-files or helm-multifiles

3) When toggling to bookmark from helm-find-files

Do you need it to be loaded from somewhere else ?

helm-mini perhaps ?


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Now helm-bookmark should load when calling helm-mini as well.
However in both `helm-mini-default-sources` and `helm-for-files-preferred-list` one can add there any source coming from any library (even external) and there is no way to know where this particular source is coming from.
One solution for this is to provide each element of theses variable as a cons cell specifying the source and the library it belongs to, e.g:
```elisp
    (setq sources
          (cl-loop for (source . lib) in helm-mini-default-sources
                   do (require lib)
                   and collect source))
```

That's mean that with such change, user having customized setting of these variables will have an error because they have a list of sources instead of an alist specifying `(source . lib)`.

**Comment by Ambrevar** [comment]
Good guess: my issue was with bookmarks used as sources in `helm-mini`.
Since there is no way for helm to guess it, I suggest you document the change.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Good guess: my issue was with bookmarks used as sources in helm-mini.
> Since there is no way for helm to guess it, I suggest you document the change.

I have now documented helm-for-files-preferred-list and
helm-mini-default-sources.

The best as I said earlier would be to use an alist for these variables
where each element would specify the libray to use e.g

    '((helm-source-foo . helm-foo))

However this is an incompatible change that would break config of many
users.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Documentation have been updated.
Using #1848 approach will confuse everybody so I prefer forgetting this idea for now.
