### ISSUE TITLE
Question: helm-find-file, downgrade current buffer score

### ISSUE THREAD

**Issue by wizmer** [emacs-helm/helm#1960]
Hi there,

First of all thank you all for contributing to helm, probably the best Emacs package.
I was wondering is there was a way to make helm proposes me the current buffer when calling helm-find-file only as a last resort. That would make sense because usually you don't want to open the buffer you are already in.

A simple example (made with a vanilla Spacemacs):
`mkdir test && cd test && touch test.cpp && test.h`
open test.h, call helm-find-file, type "test".
The first proposed result is test.h, which is the file we are already in.

Does anyone as the correct sort function to apply ?

Thanks !

**Comment by thierryvolpiatto** [comment]
Benoit Coste <notifications@github.com> writes:

> I was wondering is there was a way to make helm proposes me the
> current buffer when calling helm-find-file only as a last resort. That
> would make sense because usually you don't want to open the buffer you
> are already in.

When you start helm-find-files, the current buffer is preselected
if helm-ff-no-preselect is nil (default), you can start at the root of
directory when non nil.
For what is matching, helm doesn't take in account the current buffer
because what we are doing here is file completion and a file can be open
in a buffer or not, also if you are in this current buffer, it is you
are working on it and want to do some actions on it (copy, rename etc...).

> A simple example (made with a vanilla Spacemacs):
> mkdir test && cd test && touch test.cpp && test.h
> open test.h, call helm-find-file, type "test".
> The first proposed result is test.h, which is the file we are already in.

And it is what is expected, because if what you really want to search is
"test.h" and you have in same directory "test1.h" "test2.h" etc... when
you type "test" you want to have the file named "test.h" popping up in
first position.
It is the case in the helm directory where when I type "helm" I want to
see in first position "helm.el" and not "helm-somethingelse".

> Does anyone as the correct sort function to apply ?

If you want to bind a new sort function, you have to modify
the `filtered-candidate-transformer` of helm-find-files source and use
your function instead of `helm-ff-sort-candidates`, see
https://github.com/emacs-helm/helm/wiki/FAQ#why-is-a-customizable-helm-source-nil
and
https://github.com/thierryvolpiatto/emacs-tv-config/blob/master/init-helm-thierry.el#L316

for how to modify helm attributes.

Hope that help.

Thanks.

--
Thierry

**Comment by wizmer** [comment]
Just wanted to say thanks for your very informative answer :)
