### ISSUE TITLE
Issues on latest helm with unset variables; enter directories

### ISSUE THREAD

**Issue by quicknir** [emacs-helm/helm#1965]
On the latest helm I've encountered a bunch of issues. The variables `setq helm-boring-file-regexp-list`
  `helm-initial-frame` seem unset, but are used, resulting in errors when I try to use various functions like helm-mini and helm-find-files. I have to set the former to `nil` and the latter to `(selected-frame)` to have things work.

Then, in helm-find-files, with a directory selected, the persistent action no longer enters the directory, but instead opens it in dir. This makes helm-find-files basically unusable for me.

This is being used via spacemacs, but things were fine until I got the latest helm. It's possible that spacemacs is misconfiguring things somehow, but I'm not sure how it would have come about.

**Comment by quicknir** [comment]
I'm seeing some weird things on my end, I'm going to try to get a cleaner repro. I will close this for now.

**Comment by JRigotti** [comment]
I am having exactly the same problem after I've updated helm along with other packages, but using `emacs-projectile` instead of `spacemacs`. 

Did you solve this problem? `helm-find-files` is useless for me now :/

**Comment by thierryvolpiatto** [comment]
J. Rigotti <notifications@github.com> writes:

> Did you solve this problem? helm-find-files is useless for me now :/

Please start with emacs-helm.sh to reproduce your bugs.

--
Thierry

**Comment by JRigotti** [comment]
@thierryvolpiatto I couldn't manage to make the script work (didn't put much effort into to be fair). 

At the end, I've cloned `prelude` again, reinstalled everything back and it seems to be working fine again. Possibly there is some package being the culprit in the middle since me and @quicknir had the problem with the same variables.

Thanks for your with Helm, it makes my experience with emacs amazing!
