### ISSUE TITLE
dired-do-touch not work

### ISSUE THREAD

**Issue by tangxinfa** [emacs-helm/helm#1994]
## Expected behavior
`touch` a file to update modified time to now
## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
`touch` a file with helm the modified time unchanged
## Steps to reproduce (recipe)
Open a dired buffer, press `T`, then press `RET`, the file modified timestamp should change to now(the default)
## Describe versions of Helm, Emacs, operating system, etc.
Helm: 20180124.58
Emacs: 25.3.1
OS: Arch Linux
## IMPORTANT NOTE

Helm provides a script named `emacs-helm.sh` which runs Helm in a neutral
environment: no other packages and only minimal settings.

When possible, use it to reproduce your Helm issue to ensure no other package is
interfering.

To run it, simply switch to the directory where Helm is installed and call `./emacs-helm.sh`.

Thanks.

**Comment by thierryvolpiatto** [comment]
tangxinfa <notifications@github.com> writes:

> Expected behavior
>
> touch a file to update modified time to now
>
> Actual behavior (from emacs-helm.sh if possible, see note at the bottom)
>
> touch a file with helm the modified time unchanged
>
> Steps to reproduce (recipe)
>
> Open a dired buffer, press T, then press RET, the file modified timestamp should change to now(the default)

When you press T, you get a prompt with a helm-buffer completion showing
the ORIGINAL date creation of file (not current date of NOW), so at this
point if you press RET you will get the ORIGINAL date, so no change.
What you want to exit with NOW (the default) is exit with an
_empty string_, for this use C-RET (see mode line).
If you want to edit the date, press M-n to get the default in minibuffer
and modify it (you will get an error if the format you enter is
incorrect), then press RET.

I agree that using helm completion for this (one candidate) is useless
and I wonder why they use at emacs a completing-read instead of a simple
read-string to be able to edit the date in minibuffer, so if you want to
use vanilla emacs behavior (no helm completion) for this command, add it
to helm-completing-read-handlers-alist.

Also I notice a bug in emacs dired that incorrectly show no default at
all when you want to touch more than one file at once (dired marked
files).

More generally about helm, you have to understand that contrarily to
emacs vanilla what you get when pressing RET is what you have in the
completion buffer (the helm-buffer) and not what you have in minibuffer.
See https://github.com/emacs-helm/helm/wiki#helm-completion-vs-emacs-completion

HTH.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
> Also I notice a bug in emacs dired that incorrectly show no default at all when you want to touch more than one file at once (dired marked files).

It is working when cursor is on one of the files, however when cursor is at EOB dired doesn't use one of the file timestamp as default.

**Comment by tangxinfa** [comment]
Thanks, i will disable helm when do touch:

    (add-to-list 'helm-completing-read-handlers-alist '(dired-do-touch . nil))

**Comment by thierryvolpiatto** [comment]
BTW, just added a new touch action for helm-find-files
