### ISSUE TITLE
missing command (helm-write-file)

### ISSUE THREAD

**Issue by Jiehong** [emacs-helm/helm#200]
Hello,

Checking out git repo today, I've found out that C-x C-w is bound to something whose definition is void…

According to helm-config.el:

```
(kbd "C-x C-w")  --->  'helm-write-file
```

However, a grep in all the files of the repository shows that this functions isn't defined anywhere.

Therefore, I have 2 questions about that:
1. Why is this function gone? I was using it…
If it's really gone, maybe you have forgotten about cleaning helm-config.

**Comment by oracleyue** [comment]
@thierryvolpiatto 
The problem is, when I use `C-x C-w` or `C-x i`, it uses **ido** instead of **helm** by default. How could I configure it such that it uses `helm` to navigate paths? Many thanks!
![screen shot 2016-06-02 at 18 46 40](https://cloud.githubusercontent.com/assets/5046605/15753244/5daf6648-28f2-11e6-85ec-e49cc20f5f9d.png)

**Comment by thierryvolpiatto** [comment]
Zuogong Yue <notifications@github.com> writes:

> @thierryvolpiatto
> The problem is, when I use C-x C-w or C-x i, it uses ido instead of
> helm by default.

No, when helm-mode is enabled: 

C-x C-w == write-file
and
C-x i == insert-file

and both are helmized.
You can verify from ./emacs-helm.sh

Check you config. 


-- 
Thierry

**Comment by oracleyue** [comment]
@thierryvolpiatto You are right. It's a third party package who triggers the Ido mode.
