### ISSUE TITLE
`xref-find-references` behavior changed in `go-mode`

### ISSUE THREAD

**Issue by sergefdrv** [emacs-helm/helm#2041]
## Expected behavior

`xref-find-references` shows the similar results no matter if `helm-mode` is active

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

With `heml-mode` is active, `xref-find-references` asks for tag table, otherwise shows symbol references

## Steps to reproduce (recipe)

* Open golang source code
* Make sure `go-mode` is enabled
* Position point at a symbol
* Invoke `xref-find-references`

## Describe versions of Helm, Emacs, operating system, etc.

* Helm 2.9.4
* Emacs 25.3.50.2

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):

No, I use Helm from MELPA package

## IMPORTANT NOTE

Helm provides a script named `emacs-helm.sh` which runs Helm in a neutral
environment: no other packages and only minimal settings.

When possible, use it to reproduce your Helm issue to ensure no other package is
interfering.

To run it, simply switch to the directory where Helm is installed and call `./emacs-helm.sh`.

Thanks.

**Comment by thierryvolpiatto** [comment]
Sergey Fedorov <notifications@github.com> writes:

> ## Expected behavior
>
> `xref-find-references` shows the similar results no matter if `helm-mode` is active
>
> ## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
>
> With `heml-mode` is active, `xref-find-references` asks for tag table, otherwise shows symbol references

Helm is not supporting actually xref, I suggest you add
xref-find-references and friends to helm-completing-read-handlers-alist
or better use something more useful like helm-etags-select or helm-gtags
(external).

> ## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):
>
> No, I use Helm from MELPA package

This have nothing to do with emacs-helm.sh, you can use it with MELPA
installation or not, it is explained below and in many places elsewhere.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
After a quick try to `xref-find-references`, it seems it is working as expected, didn't try with go, so probably your problem is specific to Go, don't know.
Also I don't really understand what emacs wants to provide with the xref-* functions, the workflow it provides seems inefficient compared to the tool we already have in Helm, maybe I am missing something?
Anyway, if something is wrong with this when helm-mode is enabled, you can use the vanilla emacs behavior by adding the xref-* command to `helm-completing-read-handler-alist`.
