### ISSUE TITLE
[Display not ready] with delay 0

### ISSUE THREAD

**Issue by apnewberry** [emacs-helm/helm#2074]
I have `helm-exit-idle-delay` set to 0 and still getting `[Display not ready]` fairly often. This happens especially when I'm using TRAMP.

Ubuntu 18.04 
Emacs 26.1 
Helm v2.9.2-16-gb72baa11

**Comment by thierryvolpiatto** [comment]
apnewberry <notifications@github.com> writes:

> I have helm-exit-idle-delay set to 0 and still getting [Display not
> ready] fairly often. This happens especially when I'm using TRAMP.

You have to understand that when you press RET helm execute the action
on the candidate which is in the helm buffer and not on the minibuffer
contents, so you have to wait the completion ends before pressing RET,
of course it may happen more often with TRAMP which may be longer to
complete (I guess you are using helm-find-files).
The message "display not ready" is not an error, it tells you that you
have no candidates yet and have to wait the helm buffer is ready before
pressing RET.


-- 
Thierry

**Comment by alphapapa** [comment]
I have been getting the "Display not ready" error for a while, also.  However, when it happens, even if I wait for candidates to display, I continue getting the error when I press RET.  I have to exit the Helm session and start a new one for it to work.

Although I admit that I haven't upgraded Helm in a while, so maybe I should do that first...  :)

**Comment by thierryvolpiatto** [comment]
alphapapa <notifications@github.com> writes:

> I have been getting the "Display not ready" error for a while,
> also. However, when it happens, even if I wait for candidates to
> display, I continue getting the error when I press RET.

From where in helm?

If you have an external helm application which is exiting on a
read-string, it should use instead helm-read-string to avoid this.

I doubt you have such problem with the applications bundled with helm, I
never had this error here.

> Although I admit that I haven't upgraded Helm in a while, so maybe I
> should do that first... :)

No change have been made on this since ages as I never had problems with
this since this time.

--
Thierry

**Comment by alphapapa** [comment]
> From where in helm?

I frequently encounter it with `helm-M-x`, actually, e.g. if I activate it (bound to `M-x`) and type a few letters (knowing which ones will select the right command) and hit RET too quickly.

**Comment by thierryvolpiatto** [comment]
alphapapa <notifications@github.com> writes:

>     From where in helm?
>    
> I frequently encounter it with helm-M-x, actually, e.g. if I activate
> it (bound to M-x) and type a few letters (knowing which ones will
> select the right command) and hit RET too quickly.

Yes this is the typical case for what I created this warning, preventing
the user hitting RET on an arbitary candidate, there is no bug here,
just a feature.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Michaël <notifications@github.com> writes:

> I have the same problem on a slow computer. I solved it by editing
> this line, adding (helm-update) after (message nil). This is what is
> done in the other occurrence of [Display not ready]. Is it a gross
> misunderstanding of how this whole thing works?

No I think it make sense to add an helm-update here too, at least when I
read the commit of the second occurence in helm-maybe-exit-minibuffer,
thanks to catch this.

--
Thierry

**Comment by michaelcadilhac** [comment]
Alright, great news Thierry, thanks.  May I ask why, then, is `helm-update` called _after_ the `sit-for`?  From a bit of experimentation, things felt smoother the other way around.

In any case, my favorite behavior would be for helm to wait for the update to finish, and then commit my RET.  If I type fast and hit RET, chances are that I know what the match will be.  There does not seem to be a way to do that, correct?

Cheers!

**Comment by thierryvolpiatto** [comment]
Michaël <notifications@github.com> writes:

> Alright, great news Thierry, thanks. May I ask why, then, is
> helm-update called after the sit-for? From a bit of experimentation,
> things felt smoother the other way around.

Perhaps, didn't try, the goal is to not lost the message "display not
ready" during 0.5s so that the user see it clearly and know he typed
faster than update.

> In any case, my favorite behavior would be for helm to wait for the
> update to finish, and then commit my RET.

No, this would be unsafe as you don't know what you will have under
selection until you see it, see issue #1750.

> If I type fast and hit RET, chances are that I know what the match
> will be.

Chances yes, but you never know what the match will be, especially if
you made a typo while typing fast.

> There does not seem to be a way to do that, correct?

Yes reverting to old behavior and come back to issue #1750.

--
Thierry

**Comment by Ambrevar** [comment]
Is this fixed then?

**Comment by michaelcadilhac** [comment]
It is, thanks.

**Comment by Congrammers** [comment]
I had this particular issue, also set
`(setq helm-exit-idle-delay 0)` within `(defun dotspacemacs/user-config ()`

I found this issue when using magit.

![display_not_found_magit](https://user-images.githubusercontent.com/10162227/55457456-801d7d00-561c-11e9-900a-1622bc757820.png)

**Comment by thierryvolpiatto** [comment]
I constantly use magit checkout and can't reproduce, please try WITHOUT spacemacs preferably starting from emacs-helm.sh.

**Comment by Congrammers** [comment]
@thierryvolpiatto ignore my issue; it was due to thousands of tags being searched. If I removed all tags locally it works just fine.

once I had some loading time for `magit-show-refs`; I already filter it though. is there any way to filter tags from being searched on magit-checkout etc?

**Comment by thierryvolpiatto** [comment]
Sorry don't understand what you are asking.

**Comment by Congrammers** [comment]
@thierryvolpiatto
I think there's a store or buffer that helm would use to search through and I believe this store also included 'git tags' as a part of it search result. is there any settings / config where I can opt-out tags from the search result? It is to improve the performance so the search feature is usable for me.

**Comment by thierryvolpiatto** [comment]
Hakim Ahmad <notifications@github.com> writes:

> @thierryvolpiatto I think there's a store or buffer that helm would
> use to search through and I believe this store also included 'git
> tags' as a part of it search result. is there any settings / config
> where I can opt-out tags from the search result? It is to improve the
> performance so the search feature is usable for me.

There is no helm implementation of what you are using with magit, the
helm completion you have is a generic completion and the candidates are
those provided by magit, see in helm documentation (C-h m) the helm-mode
node.

--
Thierry

**Comment by apnewberry** [comment]
The problem may have been resolved for me, I haven't noticed it in a while. @alphapapa are you still experiencing it?

**Comment by titaniumbones** [comment]
I have been having this issue with helm-meta-x and helm-mini. As someo thers have described, it occurs even when options have already appeared in the helm sleection buffer.  It's not oncommon to get "Display not ready" 2 or 3 times before the selection finally succeeds.  I'm not sure what I should be doing to debug this -- if anyone can point me i nthe right direciton I'd appreciate it.  thanks!

**Comment by thierryvolpiatto** [comment]
There is nothing to debug, if you read the previous posts I explain why we have such message "Display not ready".
To resume, each time you type something in minibuffer helm update its buffer, if you press RET _before_  update finish helm display a warning and decreasing the value of helm-input-delay to zero is not speeding the helm-update function.
Imagine with regular emacs completion you type TAB to have completion and immediately after type RET without looking at the completion results, this is the same with helm, you have to wait completion finish before typing RET to execute default action.
Also the speed of completion depends of the actual resources of your computer at the time you are using helm.
Users not used to this kind of completion tend to type the exact string in minibuffer and expect (because they typed the exact string) they can type RET immediately after, no you have to wait completion finish.
HTH.

**Comment by thierryvolpiatto** [comment]
I will soon add an entry about this in FAQ on wiki.

**Comment by titaniumbones** [comment]
thanks @thierryvolpiatto . I think I misunderstood the earlier comments.  So it's not enough for the completion to *display*; instead, helm has to *finish calculating the completion list*, which may take quite a while -- is that correct?

I think the confusion for me is particular notable in helm-m-x and helm-mini because the emacs default behaviour is so very fast in those cases -- `M-x C-p` immediately gives one the previous commands, for instance, and `C-x b RET` switches to the previously used buffer.  At least that's what my fingers remembber.

**Comment by thierryvolpiatto** [comment]
Matt Price <notifications@github.com> writes:

> thanks @thierryvolpiatto . I think I misunderstood the earlier
> comments. So it's not enough for the completion to display; instead,
> helm has to finish calculating the completion list, which may take
> quite a while -- is that correct?

Yes and no, for most helm command a synchronous source is used, so as
soon as results popup in helm-buffer the calculation (helm-update) is
finish. But you may have other results (e.g. with M-x) when there is two
sources and one source complete faster than the other.

> I think the confusion for me is particular notable in helm-m-x and
> helm-mini because the emacs default behaviour is so very fast in those
> cases -- M-x C-p immediately gives one the previous commands,

I think you mean M-x M-p.

In this case there is no completion done, so of course it is faster.

Emacs vanilla is not faster, it is just different, with
emacs vanilla RET execute the command that is in minibuffer whereas helm
execute the command selected in the helm-buffer.

You have to understand that with Helm, it is just like in Emacs vanilla
if at each character you enter in minibuffer you press TAB afterward.

So to take advantage of this, you have to look at what helm display
after each update, you generally have to type less characters to have
what you expect e.g. with M-x you can type "emve" to get emacs-version
or "em ve" if fuzzy is disabled. 

> for instance, and C-x b RET switches to the previously used buffer. At
> least that's what my fingers remembber.

Same as above Emacs send you in minibuffer the last buffer used, so here
again no completion is done until you hit TAB, so of course it is faster.


--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
