### ISSUE TITLE
Helm dynamic sources

### ISSUE THREAD

**Issue by CeleritasCelery** [emacs-helm/helm#2094]
I was wondering if it is possible to create dynamic sources. I know that normally sources are generated beforehand and passed into helm. However I was looking at `helm-multi-swoop` which is given a list of buffers and it creates a source for each. You can then see your search results broken out by buffer. I was thinking this could work really well with something like `helm-grep`. If you could create sources dynamically you could create one for each file. This would visually clean up the buffer (you don't need to reprint the filename on each line) and you use `C-o` to jump between files. It seems like a scenario where the power of helm could really shine. Are dynamic sources possible in the current implementation of helm?

**Comment by thierryvolpiatto** [comment]
Troy Hinckley <notifications@github.com> writes:

> I was wondering if it is possible to create dynamic sources. I know
> that normally sources are generated beforehand and passed into
> helm. However I was looking at `helm-multi-swoop` which is given a
> list of buffers and it creates a source for each.

helm-swoop is not a good example.

> You can then see your search results broken out by buffer. I was
> thinking this could work really well with something like
> `helm-grep`. If you could create sources dynamically you could create
> one for each file. This would visually clean up the buffer (you don't
> need to reprint the filename on each line) and you use `C-o` to jump
> between files. It seems like a scenario where the power of helm could
> relay shine. Are dynamic sources possible in the current
> implementation of helm?

Yes, see helm-imenu-in-all-buffers or helm-descbinds, but for async
sources it would be more difficult.


--
Thierry

**Comment by CeleritasCelery** [comment]
> Yes, see helm-imenu-in-all-buffers or helm-descbinds, but for async
sources it would be more difficult.

Are you saying that it would be possible but hard to do, or that it is not implemented?

**Comment by thierryvolpiatto** [comment]
I think it is possible, never tried though.
Note it will create a process for each file so I don't think it is a good idea.

**Comment by thierryvolpiatto** [comment]
wailo <notifications@github.com> writes:

> What if the source is a process that generates output constantly, for
> example: a network socket or a process that emits output constantly
> like log command in Mac OS, helm buffer is then updated
> automatically/dynamically by appending new data until the buffer reach
> a set limit.  Would something like this works?

It works like any emacs process with a process-filter, the process
buffer being the helm-buffer.

--
Thierry

**Comment by dustinlacewell** [comment]
I was just working on a Helm frontend for a dictionary. The problem I run into is that all of the candidates must be provided up-front. This is many thousands of words, even if there is a configurable limit of how many to show, it still slows down performance quite a lot. I dream of a way to have the user's input drive candidates from my own function, instead of depending on Helm to do matching and filtering. Until then, my dictionary shall be ever sluggish.

**Comment by CeleritasCelery** [comment]
Can you make the backend async? You don’t need dynamic sources to do that

**Comment by dustinlacewell** [comment]
An async backend simply produces the initial results asynchronously correct? It doesn't receive the user input each time the user changes it, allowing the async source to produce a new set of candidates.

I am looking for Ivy's `dynamic-collection`: When non-nil, `collection` will be used to dynamically generate the candidates each time the input changes, instead of being used once statically with all-completions to generate a list of strings.

**Comment by CeleritasCelery** [comment]
> An async backend simply produces the initial results asynchronously correct? It doesn't receive the user input each time the user changes it, allowing the async source to produce a new set of candidates.

No it updates asynchronously every time the user changes its input. Similar to ivy’s Dynamic collections.

**Comment by dustinlacewell** [comment]
Doesn't that actually require an external process? I just want to run an elisp function everytime the input changes.
