### ISSUE TITLE
helm-recentf does not show org mode files neither log files

### ISSUE THREAD

**Issue by tomasorti** [emacs-helm/helm#2130]
## Expected behavior
To list `.org` & `.log` files

## Steps to reproduce (recipe)
Open a `.org` file and a `.log` file.  
Then try `helm-recentf` and `recentf-open-files`.  
Former does not show them, but the later does.

## Describe versions of Helm, Emacs, operating system, etc.
"GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 2.24.32)
helm-20180114.2330
Windows Subsystem for Linux on Windows 10

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):
Yes.

**Comment by thierryvolpiatto** [comment]
nephewtom <notifications@github.com> writes:

> Expected behavior
>
> To list .org & .log files
>
> Steps to reproduce (recipe)
>
> Open a .org file and a .log file.
> Then try helm-recentf and recentf-open-files.
> Former does not show them, but the later does.

When you open a file, if you want this file to be recorded by recentf,
you have to enable recentf-mode otherwise the file is NOT recorded.
So if you open a file (any file doesn't matter the extension) and then
call helm-recentf, your file is indeed not shown, but recentf is now
enabled (helm-recentf enable recentf-mode in its init function), if you
open another file from now, your file will be recorded.
If you want to see you file immediately in helm-recentf, enable
recentf-mode in your init file, even better don't use recentf at all and
use directly file-name-history (recentf is just an interface to
file-name-history). You can access it from helm-find-files with `C-c h`.

> Describe versions of Helm, Emacs, operating system, etc.
>
> "GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 2.24.32)
> helm-20180114.2330
> Windows Subsystem for Linux on Windows 10
>
> Are you using emacs-helm.sh to reproduce this bug (yes/no):
>
> Yes.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*


-- 
Thierry

**Comment by tomasorti** [comment]
According to what I see, even though I enable `recentf-mode` in init.el function, they do not appear in `helm-recentf`, though they do when I use `recentf-open-files`.

Anyway, I will access them through `helm-find-files` shortcut `C-c h`.
