### ISSUE TITLE
helm-find-files doesn't highlight matched pattern

### ISSUE THREAD

**Issue by vbuzin** [emacs-helm/helm#2212]
## Expected behavior

matching pattern in `Helm Find Files` is highlighted using the `helm-match[-item]` face

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

`helm-find-files` doesn't use the `helm-match[-item]` face for matching pattern although it works everywhere else (buffers, `helm-M-x`, etc)

## Steps to reproduce (recipe)

`M-x helm-find-files`

## Describe versions of Helm, Emacs, operating system, etc.

Emacs 26.3
helm-20191023.651

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):

yes

## Are you using Spacemacs? (yes/no):

no

## IMPORTANT NOTE

Helm provides a script named `emacs-helm.sh` which runs Helm in a neutral
environment: no other packages and only minimal settings.

When possible, use it to reproduce your Helm issue to ensure no other package is
interfering.

To run it, simply switch to the directory where Helm is installed and call `./emacs-helm.sh`.
If necessary you can specify emacs executable path on command line with "-P" option.

Thanks.

**Comment by thierryvolpiatto** [comment]
Slava Buzin <notifications@github.com> writes:

> Expected behavior
>
> matching pattern in Helm Find Files is highlighted using the helm-match[-item] face
>
> Actual behavior (from emacs-helm.sh if possible, see note at the bottom)
>
> helm-find-files doesn't use the helm-match[-item] face for matching pattern although it works everywhere else (buffers, helm-M-x, etc)

Yes, we are using nohighlight in `helm-source-ffiles` because
highlighting matches here is not really needed and would just slowdown
helm for a few benefit, so it is not a bug, it is a behavior wanted.

If you really want it, you can enable it by adding a defmethod to your
helm configuration:

    (defmethod helm-setup-user-source ((source helm-source-ffiles))
      (setf (slot-value source 'nohighlight) nil))

After restarting emacs, you should have highlighting in HFF.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by vbuzin** [comment]
understood, thx for the prompt reply.
