### ISSUE TITLE
Weird behaviour to Emacs Commands (M-x)

### ISSUE THREAD

**Issue by jcs090218** [emacs-helm/helm#2241]
Do the old version of helm would just ignore the top `Emacs Commands history` if is not matched?

For example, I have `package-lint-current-buffer` and `helm-fuzzy-mode` on top; inside the `Emacs Commands history`. Then I `M-x` and type `byte-com` (byte-compile-file) for searching another brand new command and it is nothing related to the commands inside history. Should those command be removed too?

### Expected behavior

Only the related commands on top inside `Emacs Commands history`. If no related commands should default to first option in `Emacs Commands`.

### Actual behavior

![helm-weird](https://user-images.githubusercontent.com/8685505/69909745-bd9c0980-143a-11ea-8e5b-c18ace9f9064.png)

**Comment by thierryvolpiatto** [comment]
Jen-Chieh Shen <notifications@github.com> writes:

> Do the old version of helm would just ignore the top Emacs Commands history if is not matched?

I don't understand your question.
Looking at the screenshot you sent, of course with a pattern like
"byte-comp" you should see nothing in the history source.
My guess is that you are not using a regualr helm (i.e. emacs-helm.sh)
and if helm-fuzzy-mode is in your history, you are using an external
package that provide this unknow mode which probably doesn't support new
helm-M-x code.
helm-M-x is now completion-styles compliant, so if you want fuzzy
matching with it, you have to configure completion-styles with one style
that provide such functionality, that is flex or helm-flex, check which
one is available in completion-styles-alist.

If you want further help on this, provide a bug report following the bug
report template, for now I know nothing about your configuration, which
emacs version you are using, which helm version etc...

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by jcs090218** [comment]
What do you mean regular helm? I have my configuration written from scratch and have installed helm from `melpa`.

I guess the recent updates have changed helm's behaviour. And `helm-fuzy` have nothing to do with this because it won't work even I disabled `helm-fuzzy` plus the previous version of helm works good with `helm-fuzzy`.

The point is, <b>it was working</b>... Isn't this obvious enough for you to know what changes and what not?

You want a detail report I will post it on next post because I don't have a linux machine with me now. I run on Windows. Thanks.

**Comment by jcs090218** [comment]
I don't know by running this would be the same as running the clean helm.

### All configuration
![helm2](https://user-images.githubusercontent.com/8685505/69911094-ee873900-1450-11ea-966f-d6f055833cf6.png)

### Result
![helm1](https://user-images.githubusercontent.com/8685505/69911096-f8a93780-1450-11ea-98c6-994116aeb944.png)

### Environment
**OS:** Windows 10
**Emacs:** 26.3
**helm:** I update package everyday hence the latest version.

**Comment by thierryvolpiatto** [comment]
Jen-Chieh Shen <notifications@github.com> writes:

> What do you mean regular helm? I have my configuration written from
> scratch and have installed helm from melpa.

I want the bug reports made WITHOUT your configuration, but with a basic
configuration.  With window that would be (require 'helm-config) and
nothing else.

> I guess the recent updates have changed helm's behaviour.

The recent update have may be changed your helm's configuration
behavior, that's different.

> And helm-fuzy have nothing to do with this because it won't work even
> I disabled helm-fuzzy plus the previous version of helm works good
> with helm-fuzzy.

It have to do with this, it is working fine but NOT with your
configuration which is not adapted to new code.

> The point is, it was working... Isn't this obvious enough for you to
> know what changes and what not?

No, "not working" means nothing.


--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Now I think I understand what you mean.
Now helm is using by default `completion-styles` and helm-M-x is affected by this.
Some completion-styles are not properly working with helm and are not useful anyway in the helm context, for your use case, it was emacs22 style, I made a list of incompatible styles and use it when setting up styles for helm and your bug gone away.

Now if you want fuzzy matching in helm-M-x, set completion-styles like this:
`(setq completion-styles '(helm-flex))` ; Emacs-26
or like this:
`(setq completion-styles '(flex))` ; Emacs-27

**Comment by jcs090218** [comment]
Thank you! I really appreciate how much effort you put into this package, but I would recommend you work on compatibility and stability. I really hate something changes, but not letting the users know what changes. 

For instance, 
#2204 - This is okay.
#2209 - This somehow happens? Next time I upgrade `helm` and it resolved.
6046600 - I'm not the only one who complains about this. It took me a long time to look into your code and see what changes to understand what has changed.

I don't mind to give you a proper bug report, but something that just doesn't seems right and it kept happening. Anyway, Thanks for replying this!

**Comment by thierryvolpiatto** [comment]
Jen-Chieh Shen <notifications@github.com> writes:

> Thank you! I really appreciate how much effort you put into this
> package, but I would recommend you work on compatibility and
> stability. I really hate something changes, but not letting the users
> know what changes.

I generally document all changes, but final documentation happens when
releasing helm version.
I can't document something before knowing exactly how it will work, for
instance completion-styles implementation is nearly finished in helm but
not in emacs itself, and once it will be finished in emacs, helm
behavior may change again, this is why it is not fully documented.
I say "fully" because it is actually documented in various docstrings.
If I develop only in a development branch, I miss many bugreports like
this one that help me a lot.
If you really want stability, use melpa-stable.

> For instance,
> #2204 - This is okay.

I agree I made this change on request of somebody to be kind without
checking if it was working properly.

> #2209 - This somehow happens? Next time I upgrade helm and it
> resolved.

Never understood what was going wrong.

>
> 6046600 - I'm not the only one who complains about this. It took me a
> long time to look into your code and see what changes to understand
> what has changed.

https://github.com/emacs-helm/helm/releases/tag/v3.3

Same here I made this change to make people happy and now I have more
people unhappy... Sometimes wondering why I make such efforts to make
users happy.

--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by manuel-uberti** [comment]
FWIW, I am happy to test new developments. I know things may break, but I always track the latest developments of the packages I use (and of Emacs itself, by the way).

I am thankful for all your efforts, Thierry, and as much as I can understand a user complaining because of something broken, I am also glad you are working to leverage `completion-styles` (among plenty of other things).

Making everyone happy is impossible, of course, but don't let that be a detriment to what you have achieved with all your work. I don't think I have any more words of praise for Helm, psession, helm-ls-git, and even bits of your own Emacs configuration. Just keep up the good work, that's all I can say. :)

**Comment by jcs090218** [comment]
> I generally document all changes, but final documentation happens when
releasing helm version.
I can't document something before knowing exactly how it will work, for
instance completion-styles implementation is nearly finished in helm but
not in emacs itself, and once it will be finished in emacs, helm
behavior may change again, this is why it is not fully documented.
I say "fully" because it is actually documented in various docstrings.
If I develop only in a development branch, I miss many bug reports like
this one that help me a lot.
If you really want stability, use melpa-stable.

Thanks for letting me know. I will consider using mepla-stable

> Same here I made this change to make people happy and now I have more
people unhappy... Sometimes wondering why I make such efforts to make
users happy.

I think isn't about making people happy or unhappy. I would say maybe just commit the work carefully and make sure everything work before you make commitment? Or ask people to join the development and maintain it together? And again, I really appreciate you maintain helm but I can say the development workflow can be better?

**Comment by codygman** [comment]
I was affected by this as well, but `(setq completion-styles '(flex))` fixed it for me in emacs 27. It was really frustrating to have to `C-o` every time instead of helm working correctly.

I guess I unwittingly unpinned my previous helm version without checking though. I wish there were a way to surface this change better to users in this situation, but I guess there isn't after reading everything.

**Comment by thierryvolpiatto** [comment]
Cody Goodman <notifications@github.com> writes:

> I was affected by this as well, but (setq completion-styles '(flex))
> fixed it for me in emacs 27. It was really frustrating to have to C-o
> every time instead of helm working correctly.
>
> I guess I unwittingly unpinned my previous helm version without
> checking though. I wish there were a way to surface this change better
> to users in this situation, but I guess there isn't after reading
> everything.

M-x C-h m

What's the problem?

--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
