### ISSUE TITLE
helm-flex causes "Company: An error occurred in auto-begin"

### ISSUE THREAD

**Issue by zzp0** [emacs-helm/helm#2270]
## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
```
Company: An error occurred in auto-begin
Company: backend company-capf error "No buffer named *helm*" with args (candidates pam)
```
## Steps to reproduce (recipe)
`./emacs-helm.sh`
*In scratch buffer*
```
(load "/path/.emacs.d/elpa/company-20200110.1729/company-autoloads.el")
(setq completion-styles '(helm-flex))
(company-mode)
;; Enter some codes to activate company, view echo area or Messages buffer.
```
*The problem disappears when checkout commit c09329cd8bf2363266dfc2b8d6a43f91a549f0bb*
## Describe versions of Helm, Emacs, operating system, etc.
```
helm-20200122.1552
helm-core-20200122.737
company-20200110.1729
GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.10) 
OS: Manjaro Linux
```
## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):
yes
## Are you using Spacemacs? (yes/no):
no
## IMPORTANT NOTE

Helm provides a script named `emacs-helm.sh` which runs Helm in a neutral
environment: no other packages and only minimal settings.

When possible, use it to reproduce your Helm issue to ensure no other package is
interfering.

To run it, simply switch to the directory where Helm is installed and call `./emacs-helm.sh`.
If necessary you can specify emacs executable path on command line with "-P" option.

Thanks.

**Comment by thierryvolpiatto** [comment]
zzp <notifications@github.com> writes:

> Company: backend company-capf error "No buffer named *helm*" with args (candidates pam)

Should be fixed now.

Thanks.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Note also that helm-flex is a style created for helm to provide flex
completion in emacs-26, but as there is no mechanism in emacs-26 to
provide a sort function for this style you will have no sorting in other
modes than helm, so no sorting in company.
For the helm style, it needs a completion UI accepting spaces as input,
for now only helm is accepting such a style.
You can use helm-flex only in the modes where you want helm-completion
by setting your styles for this mode in helm-completion-styles-alist
instead of setting directly completion-styles, e.g.

    (add-to-list 'helm-completion-styles-alist '(foo-mode '(emacs helm-flex helm))

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by zzp0** [comment]
> Should be fixed now.

Yes, it's been fixed. 
Thank you.

>  (add-to-list 'helm-completion-styles-alist '(foo-mode '(emacs helm-flex helm))

Thanks for your advice.
