### ISSUE TITLE
Uncommon symbol on default helm-ff-cache-mode-lighter value

### ISSUE THREAD

**Issue by emb-brickabode** [emacs-helm/helm#2341]
## Expected behavior
Some recognizable string here https://github.com/emacs-helm/helm/blob/master/helm-files.el#L3234

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):
no
## Are you using Spacemacs? (yes/no):
no
## IMPORTANT NOTE

Helm provides a script named `emacs-helm.sh` which runs Helm in a neutral
environment: no other packages and only minimal settings.

When possible, use it to reproduce your Helm issue to ensure no other package is
interfering.

To run it, simply switch to the directory where Helm is installed and call `./emacs-helm.sh`.
If necessary you can specify emacs executable path on command line with "-P" option.

Thanks.

**Comment by manuel-uberti** [comment]
Sorry, can you try from `emacs-helm.sh`?

When I try from it, it seems to work fine on my system:

![Screenshot from 2020-07-16 16-45-35](https://user-images.githubusercontent.com/8199224/87685576-da940b80-c783-11ea-8e87-a727e3f9d42e.png)

**Comment by thierryvolpiatto** [comment]
emb-brickabode <notifications@github.com> writes:

> Expected behavior
>
> Some recognizable string here https://github.com/emacs-helm/helm/blob/master/helm-files.el#L3234

Install a decent set of fonts to have this unicode string or pickup an
other one or use any string you want.


-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Manuel Uberti <notifications@github.com> writes:

> Sorry, can you try from emacs-helm.sh?
>
> When I try from it, it seems to work fine on my system:

Yes, because you have the good fonts installed, otherwise you have an
unknow unicode string.
 
> Screensh
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.*


-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Note that this is not an encoding error, this is just you have not the font to display this string.

**Comment by emb-brickabode** [comment]
I think I understand the font issue now, thanks. I had already customized the symbol. 

I do suggest questioning the wisdom of using a default char that is not supported by "DejaVu Sans Mono"

**Comment by emb-brickabode** [comment]
Maybe taking a page out of mu4e and giving the user a choice to use a fancy symbol, with a default of an ASCII version? Like https://github.com/djcb/mu/blob/master/mu4e/mu4e-headers.el#L224-L234?

**Comment by emb-brickabode** [comment]
I have modified the title to reflect my new understanding

**Comment by bsuh** [comment]
For myself, the unicode character renders, but is styled like it's part of the mode line, which I find distracting and jarring.

<img width="757" alt="Screen Shot 2020-07-18 at 1 23 34 AM" src="https://user-images.githubusercontent.com/47231/87848463-a9a3fb80-c895-11ea-9ba8-d26780c23e52.png">

**Comment by Dapuva76** [comment]
Came here to ask how to remove this. I do not like having complex symbols on the modeline.

**Comment by manuel-uberti** [comment]
@Dapuva76  You can check and set `helm-ff-cache-mode-lighter-sleep`, `helm-ff-cache-mode-lighter-updating`, and `helm-ff-cache-mode-lighter` to your preferences.

**Comment by thierryvolpiatto** [comment]
Or you can set `helm-ff-keep-cached-candidates` to nil, you will loose the auto update cache stuff though.
About caching candidates in HFF please read the documentation, also the relevant variables are accessible from `C-h c`, please have a look as well.
Thanks.

**Comment by Dapuva76** [comment]
@manuel-uberti thanks, I've set it to a single character with a space in front, but the background for the space as well as the character is not dark, so the modeline looks like it has a gap.

Not sure if I have to set the background color with the variable, and how to acomplish that.

**Comment by thierryvolpiatto** [comment]
Use an empty string or nil.

**Comment by amno1** [comment]
I have just updated and I can confirm. It completely f***s my mode line. I get a rectangle which also makes modeline much taller so the underline gets almost in the middle. The trinagle is much smaller so when it switches to triangle the entire modeline squeezes. Now I have dancing/bllnking modeline :dancers:  How annoying :-). It is horrible.
It would be nice if we could do something like this (which didn't work):

                 (diminish 'helm-ff-cache-mode)

as we are used to in Emacs ecosystem.

I can confirm that setting those 3 variable as menttion above solved the problem. Thanks for the Helm and good work otherwise!

**Comment by thierryvolpiatto** [comment]
Arthur Miller <notifications@github.com> writes:

> I have just updated and I can confirm. It completely f***s my mode line. I get a rectangle which also makes modeline much taller so the underline gets almost in the
> middle. The trinagle is much smaller so when it switches to triangle the entire modeline squeezes. Now I have dancing/bllnking modeline 👯 How annoying :-). It is horrible.
> It would be nice if we could do something like this (which didn't work):
>
>              (diminish 'helm-ff-cache-mode)
>
> as we are used to in Emacs ecosystem.
>
> I can confirm that setting those 3 variable as menttion above solved the problem. Thanks for the Helm and good work otherwise!

Thanks for feedback, I am going to disable this by default.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Arthur Miller <notifications@github.com> writes:

> It would be nice if we could do something like this (which didn't work):
>
>              (diminish 'helm-ff-cache-mode)

It works here.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Thierry Volpiatto <thierry.volpiatto@gmail.com> writes:

> Thanks for feedback, I am going to disable this by default.

Done.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by amno1** [comment]
I Arthur Miller <notifications@github.com> writes:

>  It would be nice if we could do something like this (which didn't work):
> 
>               (diminish 'helm-ff-cache-mode)
> It works here.
Ok. I don't know why my Emacs didn't respect diminished. I am use-package user, so I first tryed to put it in :diminish keyword, but it didn't worked. I tryed to add hook (add-hook 'helm-ff-cache-mode (lambda () (diminish 'helm-ff-cache-mode)) but it didn't worked either, and I tried to add just plain (diminish 'helm-ff-cache-mode) somewhere in my init file, but I got it popping back all the time. I don't know why, I spent about an hour yesterday figuring it out before I did google search and discovered other also had problesm. 

I think if you gonna package feature that really on certain icons/unicode chars, then either ship those with helm, or make it optional and put requirements (like certain font) in some Readme or so. Maybe a tip with which font it is known to work well or something like that. Helm is great otherwise and it is good to you experiment with more "modern" stuff.

**Comment by thierryvolpiatto** [comment]
Arthur Miller <notifications@github.com> writes:

> I Arthur Miller notifications@github.com writes:
>
>     It would be nice if we could do something like this (which didn't work):
>    
>               (diminish 'helm-ff-cache-mode)
>     
>     It works here.
>    
> Ok. I don't know why my Emacs didn't respect diminished. I am
> use-package user, so I first tryed to put it in :diminish keyword, but
> it didn't worked. I tryed to add hook (add-hook 'helm-ff-cache-mode
> (lambda () (diminish 'helm-ff-cache-mode)) but it didn't worked
> either, and I tried to add just plain (diminish 'helm-ff-cache-mode)
> somewhere in my init file, but I got it popping back all the time. I
> don't know why, I spent about an hour yesterday figuring it out before
> I did google search and discovered other also had problesm.

Perhaps because the lighter was handling properties (a face), now I
removed the faces the lighter is a plain string without properties and
it should work better with different mode-line config, the problem is
not really that the string is a unicode symbol or not, but it have
properties.

Anyway now the default is nil for the lighter, so no more problems.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by amno1** [comment]
> Perhaps because the lighter was handling properties (a face), now I
> removed the faces the lighter is a plain string without properties and
> it should work better with different mode-line config, the problem is
> not really that the string is a unicode symbol or not, but it have
> properties.

Yes, it could be. Thanks for explaining. I guess I'll get it when it gets pushed to Melpa, for the time being, I have those 3 variables sett to nil, so everything is ok. Thanks.
