### ISSUE TITLE
Nearly impossible to get Helm to refresh Tramp candidates

### ISSUE THREAD

**Issue by posita** [emacs-helm/helm#2486]
### What happened?

I have `(global-set-key (kbd "C-x C-f") 'helm-find-files)`. When I do this over a tramp connection (e.g., `/scp:host:path` or `/docker:host:path` via `docker-tramp`), whatever candidates I expand via tab-completion for a directory persist seemingly forever. `M-x find-file` does not suffer from this problem. It will refresh its list via tab-completion upon new invocations (and even within the same invocation if you remove the directory from the path, then tab-complete "back into" it).

### How to reproduce?

1. `M-x helm-find-files` and use a Tramp path.
2. Tab complete your way into a directory where `foo.txt` doesn't exist.
3. Independently create `foo.txt` at that location.
4. `C-g` out of `helm-find-files` and re-invoke `M-x helm-find-files`.
5. Return to the same location. Note that `foo.txt` will not appear among the candidates. This behavior will persist until you kill Emacs. Even killing the tramp connections doesn't help.

### Helm Version

Last from Melpa

### Emacs Version

Emacs-27.2

### OS

MacOSX

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by thierryvolpiatto** [comment]
Matt Bogosian ***@***.***> writes:

>  2. Tab complete your way into a directory where foo.txt doesn't
>  exist.

There is no "Tab complete" in Helm.

>  
>  3. Independently create foo.txt at that location.  4. C-g out of
>  helm-find-files and re-invoke M-x helm-find-files.  5. Return to the
>  same location. Note that foo.txt will not appear among the
>  candidates. This behavior will persist until you kill Emacs. Even
>  killing the tramp connections doesn't help.

Helm is caching its candidates and watch directories with (i)notify,
probably notify is not working properly in MacOs or just not supported?
What you can do is refresh your directory with C-c C-u.

Otherwise this is not reproductible on GNU/Linux.

-- 
Thierry

**Comment by posita** [comment]
`C-c C-u` does appear to update the cache. Thank you for that. Does Helm use `inotify` over Tramp connections? (Apologies, I don't really understand that machinery.)

**Comment by thierryvolpiatto** [comment]
Matt Bogosian ***@***.***> writes:

> Does Helm use inotify over Tramp connections?

Yes, more exactly helm use inotify.el which support remote files.
Some methods may not be supported, they are listed in
`helm-ff-inotify-unsupported-methods`.

> (Apologies, I don't really understand that machinery.)

At each time you visit a directory, helm cache this directory (name
. contents), and also add a watcher on this directory.
When the directory is modified (file removed or added), the watcher
remove this directory from cache so that on next visit the cache is
created again.
 

-- 
Thierry

**Comment by posita** [comment]
If updates are not being received for Tramp connections, then how can I diagnose the issue? Does that mean `inotify` isn't available on the remote? I experience this pretty consistently with every linux remote I visit, via SSH and `docker exec`. I have never been able to get helm to update its cache of remote directory contents. How can I diagnose?
