### ISSUE TITLE
error: Running helm command outside of context

### ISSUE THREAD

**Issue by twlz0ne** [emacs-helm/helm#2529]
### What happened?

Unable to quit recursive edit in minibuffer.

![image](https://user-images.githubusercontent.com/2653486/178135565-bad2cfc7-3e2a-4fe1-a9b0-cc257d04419b.png)

### How to reproduce?

1. Run `emacs -Q -l /path/to/test-quit-recursive-minibuffer-issue.el` in terminal.
2. Type `i` in `*scratch*` buffer.
3. Press `C-M-i` to active helm completion.
4. Pres `C-\` to switch source.
5. Press `Enter` to confirm input. (cursor still in minibuffer)
6. Press `Enter` to force quit. (got message "Some times cannot exit recursive edit in minibuffer.")

<details>
<summary> Here is the **test-quit-recursive-minibuffer-issue.el** </summary>

```elisp
;;; Usage: emacs -nw -Q -l /path/to/test-quit-recursive-minibuffer-issue.el
;;; Date: 2022-07-09_11.29.08

;; ---------------------------------------------------------------------------
;; elpa

(require 'seq)

(setq user-emacs-directory
      (car (seq-filter
            #'file-exists-p
            (list (format "~/.emacs.d/%s/" emacs-version)
                  (format "~/.emacs.d/%s/" emacs-major-version)
                  "~/.emacs.d/"))))

(setq package-user-dir (concat user-emacs-directory "elpa/"))

(package-initialize)

;; ---------------------------------------------------------------------------
;; test config

(require 'yasnippet)
(require 'helm-mode)
(require 'helm-c-yasnippet)

(defvar last-source nil)
(defvar curr-buffer nil)

(defun swith-source ()
  (interactive)
  (let ((source last-source))
    (setq last-source (helm-get-current-source))
    (unless curr-buffer (setq curr-buffer helm-current-buffer))
    (with-current-buffer curr-buffer
      (if source
          (helm source)
        (helm-yas-complete)))))

(add-to-list 'completion-at-point-functions 'helm-lisp-completion-at-point)
(define-key minibuffer-mode-map (kbd "M-\\") #'swith-source)
(minibuffer-depth-indicate-mode 1)
(yas-global-mode 1)
;; (toggle-debug-on-error)

;;; test-quit-recursive-minibuffer-issue.el ends here
```
</details>

### Helm Version

Melpa or NonGnuElpa

- helm-20220709.1652
- helm-core-20220708.343
- helm-c-yasnippet-20210330.16

### Emacs Version

Emacs-28/29

### OS

MacOSX 10.13.6

### Relevant backtrace (if possible)

```
Debugger entered--Lisp error: (error "Running helm command outside of context")
  signal(error ("Running helm command outside of context"))
  error("Running helm command outside of context")
  helm-keyboard-quit()
  funcall-interactively(helm-keyboard-quit)
  call-interactively(helm-keyboard-quit nil nil)
  command-execute(helm-keyboard-quit)
  read-from-minibuffer(#("pattern: " 0 9 (face helm-minibuffer-prompt)) "i " (keymap (f12 . #f(compiled-function () (interactive nil) #<bytecode 0x1fd8649ec935a80>)) (f11 . #f(comp$
  helm-read-from-minibuffer(nil "i " nil noresume nil nil nil)
  helm-internal(((name . "Lisp completion") (init #f(compiled-function () #<bytecode -0x11c4077fabe1bfb4>)) (candidates . helm-candidates-in-buffer) (keymap keymap (f12 . #f(compil$
  apply(helm-internal (((name . "Lisp completion") (init #f(compiled-function () #<bytecode -0x11c4077fabe1bfb4>)) (candidates . helm-candidates-in-buffer) (keymap keymap (f12 . #f$
  helm(((name . "Lisp completion") (init #f(compiled-function () #<bytecode -0x11c4077fabe1bfb4>)) (candidates . helm-candidates-in-buffer) (keymap keymap (f12 . #f(compiled-functi$
  apply(helm (((name . "Lisp completion") (init #f(compiled-function () #<bytecode -0x11c4077fabe1bfb4>)) (candidates . helm-candidates-in-buffer) (keymap keymap (f12 . #f(compiled$
  helm(:sources ((name . "Lisp completion") (init #f(compiled-function () #<bytecode -0x11c4077fabe1bfb4>)) (candidates . helm-candidates-in-buffer) (keymap keymap (f12 . #f(compil$
  helm-lisp-completion-at-point()
  completion--capf-wrapper(helm-lisp-completion-at-point all)
  run-hook-wrapped(completion--capf-wrapper helm-lisp-completion-at-point all)
  completion-at-point()
  funcall-interactively(completion-at-point)
  call-interactively(completion-at-point nil nil)
  command-execute(completion-at-point)
```

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by thierryvolpiatto** [comment]
twlz0ne ***@***.***> writes:

> What happened?
>
> Unable to quit recursive edit in minibuffer.

Sorry but I don't understand what is happening, I will not try your
recipe which use deprecated packages, also I don't understand
what do you want to achieve with your helm-switch-source function,
please clarify what you want to do.

Thanks.

-- 
Thierry

**Comment by twlz0ne** [comment]
The switch-source function just used to help reproduce the issue which occurs rather randomly, looks like the helm state is corrupted so that is unable to quit the recursive edit in minibuffer.

Maybe I'll find a "normal" way to reproduce it later.

**Comment by ashmanskas** [comment]
This "running helm command outside of context" issue happens to me about once a week.  I have not yet narrowed it down.  It seems to happen if I move the mouse outside of the frame while helm is waiting for input.  What is most annoying is that control-G does not get me out of this.  It seems extremely un-emacs-like to be stuck in some sort of modal dialog that repeated control-G will not escape from.  (Loyal non-expert emacs user since 1986.  I installed emacs on our high-school VAX-11/785 running VMS.  Helm user for only a few years, still at helm novice stage.)

**Comment by michael-heerdegen** [comment]
Bill Ashmanskas ***@***.***> writes:

> This "running helm command outside of context" issue happens to me about
> once a week. I have not yet narrowed it down. It seems to happen if I move the
> mouse outside of the frame while helm is waiting for input. What is most
> annoying is that control-G does not get me out of this.

That happens by default for me (emacs-helm.sh) if another frame gets
input focus.  ESC ESC ESC - the /really/ ultimative "get me out" command,
does get me out, though.

**Comment by ashmanskas** [comment]
Thank you so much!  ESC ESC ESC indeed works!  It would never have occurred to me to use this, rather than C-g, to "get me out" of something in emacs, particularly since an  ESC prefix is usually a synonym for using the meta key.

**Comment by thierryvolpiatto** [comment]
Bill Ashmanskas ***@***.***> writes:

> This "running helm command outside of context" issue happens to me
> about once a week. I have not yet narrowed it down. It seems to happen
> if I move the mouse outside of the frame while helm is waiting for
> input.

This warning is meaningful, it say you are running an helm action
outside a helm session, don't know how you can produce this though.

> What is most annoying is that control-G does not get me out of
> this.

Of course you have first to gain focus to the minibuffer in use.

> It seems extremely un-emacs-like to be stuck in some sort of modal
> dialog that repeated control-G will not escape from.

It is not "un-emacs-like", start from emacs -Q, eval
(read-from-minibuffer "test: "), click outside the minibuffer and hit
C-g as many times as you want, you will not disable the active
minibuffer. What you have to use in such cases is C-] (abort-recursive-edit).

-- 
Thierry

**Comment by ashmanskas** [comment]
Thank you so much!  ESC ESC ESC indeed works!  It would never have occurred to me to use this, rather than C-g, to "get me out" of something in emacs, particularly since an  ESC prefix is usually a synonym for using the meta key.

=====

Thierry's response is also informative — thank you.  Despite 36 years using emacs as my main editor, I had never before had occasion to use 'abort-recursive-edit' or 'keyboard-escape-quit' both of which get me out of this tricky state.  I'll add these commands to my emacs Anki deck.

**Comment by michael-heerdegen** [comment]
Bill Ashmanskas ***@***.***> writes:

> I'll add these commands to my emacs Anki deck.

You might as well want to add the `top-level' command.

**Comment by zan-xhipe** [comment]
I keep running into this error when trying to kill buffers.  ESC ESC ESC doesn't work for me

**Comment by thierryvolpiatto** [comment]
@zan-xhipe Please provide a recipe describing exactly what you do, thanks.
(preferably from emacs-helm.sh).

**Comment by Addlai** [comment]
I recently installed helm. I'm also experiencing this problem, but none of the above suggestions get me out. Ctrl-g, Ctrl-], Esc Esc Esc, clicking various places with the mouse, etc., all have no effect. I have to kill and restart Emacs.

This is really unfortunate, considering the time it took me to set up helm.

I will check back once some time over the next month to see if there are any questions which I can answer, but unfortunately I probably won't be able to try suggestions (since I will un-install helm as soon as I post this message).

**Comment by thierryvolpiatto** [comment]
Robert Morelli ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
> I recently installed helm. I'm also experiencing this problem, but
> none of the above suggestions get me out. Ctrl-g, Ctrl-], Esc Esc Esc,
> clicking various places with the mouse, etc., all have no effect.

Probably because you are using a non standard emacs configuration, if
you were using a minimal helm config with preferably emacs-helm.sh and
read carefully this thread from the beginning, you would see that Helm
is working perfectly.
Also if you want help, describe exactly what you are doing, starting
from emacs-helm.sh.

> This is really unfortunate, considering the time it took me to set up
> helm.

This is probably the problem... Helm configuration should be 1 or 2
lines long at first, please read the wiki.

-- 
Thierry
