### ISSUE TITLE
Allow switching to a buffer nested in a tab-line under some tab.

### ISSUE THREAD

**Issue by crocodile-dentist** [emacs-helm/helm#2684]
### Suggestion

Currently, helm allows switching to a buffer in another tab, but it would be convenient if there was an option to allow it to also inspect the nested tab line buffers and switch if indeed the buffer is "hiding" there. 

### Description

See above.

### Solutions

An extension to the current mechanism

**Comment by thierryvolpiatto** [comment]
If I understand correctly what you want, it is what `helm-buffers-maybe-switch-to-tab` does, isn't it?

**Comment by crocodile-dentist** [comment]
I had that on, and it works only when a buffer in question is in focus on some tab, but not when it is only a tab returned by eg. `tab-line-tabs-window-buffers`. I suppose the right check could be added to https://github.com/emacs-helm/helm/blob/master/helm-utils.el#L320-L343?

**Comment by thierryvolpiatto** [comment]
Marcin Wójtowicz ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
> I had that on, and it works only when a buffer in question is in focus
> on some tab, but not when it is only a tab returned by
> eg. tab-line-tabs-window-buffers.

I am not sure to understand what you mean, I am not using tabs
personally.  Could you provide a recipe to reproduce what is not working?

> I suppose the right check could be added to
> https://github.com/emacs-helm/helm/blob/master/helm-utils.el#L320-L343?

Don't know what to change here as long as I don't yet understand what's
wrong.


Thanks.

-- 
Thierry

**Comment by crocodile-dentist** [comment]
Is it really so bad? If the user wants a new tab with A, he can create one manually and open A in it. To me the customization option Helm Buffers Maybe Switch To Tab when set to on may be interpreted as a preference to jump to a tab if it is opened already somewhere, and otherwise to open a new tab. Another option is to combine with a prefix to temporarily toggle this preference? So C-u C-c C-t would flip the boolean, and act accordingly.
The tab line can be customized. It can contain all major mode buffers, or just the windows that were opened under some tab (for organization purposes) and one can bury buffers from the tab-line without closing them. I find it very helpful when I'm working on a small group of files that I have to toggle frequently and have bound F6 and F7 to quickly move back and forth.

**Comment by thierryvolpiatto** [comment]
Marcin Wójtowicz ***@***.***> writes:

> Is it really so bad?

Yes, this will not work reliabily with marked buffers, among other
things, if we want this we have to completely change the current
behavior, IOW rewrite mostly all.

If you were able to switch to a buffer which is not the current-buffer
in a tab (with RET) would it be acceptable for you?

Can you try:

(customize-set-variable 'tab-bar-tab-name-function #'tab-bar-tab-name-all)

and jump to your buffer with RET.

Let me know if it work as expected for you.

NOTE: Since I wrote the current code (emacs-27 IIRC), tab-bar code has
changed a lot, using now a lot of unexpected side effects, so
let-bounding tab-bar-tab-name-function like we did is no more an option.


> If the user wants a new tab with A, he can create one manually and
> open A in it. To me the customization option Helm Buffers Maybe Switch
> To Tab when set to on may be interpreted as a preference to jump to a
> tab if it is opened already somewhere, and otherwise to open a new
> tab. Another option is to combine with a prefix to temporarily toggle
> this preference? So C-u C-c C-t would flip the boolean, and act
> accordingly.  The tab line can be customized. It can contain all major
> mode buffers, or just the windows that were opened under some tab (for
> organization purposes) and one can bury buffers from the tab-line
> without closing them. I find it very helpful when I'm working on a
> small group of files that I have to toggle frequently and have bound
> F6 and F7 to quickly move back and forth.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.*Message ID: ***@***.***>

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
I made a compromise by changing the behavior of `C-c C-t`:
Now if you mark several buffers and hit `C-c C-t` helm makes a new tab and displays these buffers in separate windows in this tab.
If you hit `C-c C-t` on a single buffer (or there is only one marked) helm switch to this buffer in its tab if some, otherwise display it in a new tab.
