### ISSUE TITLE
Input using thing-at-point should be appended into Helm prompt=

### ISSUE THREAD

**Issue by tuhdo** [emacs-helm/helm#491]
`helm-sources-using-default-as-input` allows to select `thing-at-point` as input, but this input is not available in Helm prompt. For example, I add `helm-source-occur` so I can select symbols at point for quick searching. But, the selected input does not appear in `pattern:` prompt, and if I want to modify the input slightly I will have to type the whole thing.

**Comment by aligua** [comment]
After whole 4 years, I  see a solution match exactly initial need of this issue reporter, share it here:

https://emacs.stackexchange.com/questions/10731/partial-input-to-interactive-command

The above link describes a way to automatically input any string into minibuffer *just* after the interactive helm command executed. 
Thus with some extension it would fit in this issue's initial need.

**Comment by acowley** [comment]
When I invoke `helm-occur` with point at a symbol of interest, the current line in the original buffer is the highlighted line in the helm occur buffer (letting me see search results around point). If I now want to refine the search, I can hit `M-n` to populate the mini-buffer. But when I edit the pattern, the highlighted line in the helm occur buffer moves to the first matching line in the original buffer. 

My scenario is that I move point to an interesting word in a large file, invoke `helm-occur`, but now want to refine the pattern with my attention still centered at the original location of point. Is there a way to preserve that location in the helm occur buffer?

**Comment by thierryvolpiatto** [comment]
Anthony Cowley <notifications@github.com> writes:

> My scenario is that I move point to an interesting word in a large
> file, invoke helm-occur, but now want to refine the pattern with my
> attention still centered at the original location of point. Is there a
> way to preserve that location in the helm occur buffer?

No, but once you hit M-n, what you can do is hit C-! before editing
pattern to prevent updating, once you have completed your pattern hit
C-! again.

Also what you can do is jump to the interesting line, mark a region from
this line and run again helm-occur on this region (you should have your
previous pattern by hitting M-p).

--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by acowley** [comment]
Thanks for the suggestions, @thierryvolpiatto. The C-! approach still doesn't keep the original line selected for me. helm-swoop has the behavior I'd like, so I'll look at how it handles initial input to see if it makes sense / is possible to wrap helm-occur to work that way. 

I understand the reasoning you gave here for not initially populating the minibuffer, so I will need to figure out how current line is held during a normal pattern update to determine why it is lost when used this way.

**Comment by thierryvolpiatto** [comment]
Anthony Cowley <notifications@github.com> writes:

> I understand the reasoning you gave here for not initially populating
> the minibuffer, so I will need to figure out how current line is held
> during a normal pattern update to determine why it is lost when used
> this way.

Using :input or :default is the same, what you want is another
preselection after updating minibuffer, the only difference with
helm-swoop is that it use :input so the preselection is done.
That say why do you want to keep the original line when inserting input
(which is the same as default) if you want to modify it, which will
trigger helm-update (with swoop as well).

> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.*


--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by acowley** [comment]
I now realize that this is a more general `helm-occur` design point that I just usually run into with the initial pattern. Here is an example buffer,

```
foo
temperature 99 alert
temperature 98
temperature 100 alert
bar
temperature 97
temperature 102 alert
baz
```

I move point to the word `temperature` on the fourth line. I trigger `helm-swoop` and the lines that include the word `temperature` are returned with line four being focused. If I then type ` alert`, the three lines (2, 4, and 7) including the words `temperature` and `alert` are returned, still with line four in focus.

This sometimes comes up for me when navigating source code, but most often when working with large log files. I will find a word of interest in the log file, trigger the search, then refine the search with other words of interest as I try to track down a change in the system. Here I care about proximity: what was the previous mention of these words of interest? What is the next mention? They may be hundreds or thousands of lines away in the file, but this interface is great for showing them on one screen.

The interaction I described doesn't work the same way with `helm-occur`, since when a search is refined in `helm-occur`, the focus is moved. I almost always use `helm-swoop` or `helm-occur` to search for the symbol at point, which made me think that was the issue here.

**Comment by rileyrg** [comment]
Years later I too agree that thing at point should be the default and preselected  - certainly have the ability to configure it so. Preselected? Yes. Then you just type over to erase it. There's some inconsistency in helm - C-h f preselects the function at point and makes it the "default" whereas C-h v doesnt.  Helm is a wonderful addition to emacs - I couldnt imagine using emacs without it now. Great stuff.
