### ISSUE TITLE
helm-M-x not as convenient as M-x

### ISSUE THREAD

**Issue by zwz** [emacs-helm/helm#495]
Originally, you can auto-complete the commands by TAB in M-x.
For example, if you hit M-x, and type "list-*-p", and then hit TAB, 
it expands to "list-load-path-shadows", which is very handy.

However, since TAB binds by default to helm-select-action,
if I (global-set-key (kbd "M-x") 'helm-M-x), 
I do not know how to do auto-completion (more like guessing) in M-x. 

Is there any workaround or configuration I missed?

**Comment by adroll-kosta** [comment]
Actually, the issue is not the usage model but rather a missed use-case that is important nevertheless - When trying to select something in helm that is similar to one of the options but isn't there; With regular tab completion, I could tab complete and then edit the result to my liking. With helm, 90% of the time one of the presented options is exactly what I need However, 10% of the time you need something that is not quite there (e.g. file name similar to an existing file name but with `.1` at the end, a bump in the minor version of a git tag in magit, etc). All these valid use cases are not served by helm and that's a shame.

**Comment by sprig** [comment]
`C-j` describes the command when in helm-M-x mode
