### ISSUE TITLE
Helm and BBDB creation issue

### ISSUE THREAD

**Issue by Jiehong** [emacs-helm/helm#78]
When I use bbdb-create to create a new contact, at one point, when I need to select the address description, helm gives me the previous one I used before, which is great.

However, when I want to keep going and when I don't want to add a new address, I should type RET to continue but that select the first helm proposition… which is very annoying. I have to disable helm in order to use bbdb-create then.

I haven't found a way to disable bbdb on the run just for that proposition. Is there a way to do that that I haven't found yet?

**Comment by behrica** [comment]
I am not sure, if my comment is still relevant.

I had the same problem as described in the first comment here.

The workaround is to type   SPACE  Return.
So entering a 'blank'. This let you get out of the endless loop.

**Comment by thierryvolpiatto** [comment]
behrica <notifications@github.com> writes:

> I am not sure, if my comment is still relevant.
>
> I had the same problem as described in the first comment here.
>
> The workaround is to type SPACE Return.
> So entering a 'blank'. This let you get out of the endless loop.

helm-bbdb is no more maintained in helm, it is here actually:

https://github.com/thierryvolpiatto/helm-bbdb

It is broken with new bbdb, it working only with old bbdb. 
As I don't use myself bbdb, 
I am waiting for somebody to fix it (and maintain it).

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by michael-heerdegen** [comment]
I didn't read all of the thread carefully, but I think all @Jiehong was missing was to hit C-RET to enter an empty string, instead of RET being mentioned in the prompt.  I know that very well because I asked the very same question two years ago or so.  Remember @thierryvolpiatto?  You said something like "Damn, look at the mode-line, it clearly says you should..." etc. at that time, and closed the issue.

I have used bbdb frequently since then, including bbdb-create, and it worked without a problem, once you have got to know to you have to use C-RET instead of RET.

So I didn't have a look at the recent changes.  Should I?  Do they make sense after what I have said?

**Comment by michael-heerdegen** [comment]
Oops, I totally missed the most of the thread is three years old.

**Comment by michael-heerdegen** [comment]
FWIW, I can fix helm-bbdb to get it work again if this is wanted, but I don't want to maintain it, too.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> I have used bbdb frequently since then, including bbdb-create, and it
> worked without a problem, once you have got to know to you have to use
> C-RET instead of RET.

Are you sure you are using helm-bbdb and not just the original bbdb
commands helmized by helm-mode ?

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> FWIW, I can fix helm-bbdb to get it work again if this is wanted, but
> I don't want to maintain it, too.

If you are using bbdb version 3+ it would be welcome. The problem is
just the new bbdb is not backward compatible with old version and I
don't know which functions to use with new bbdb, not being a bbdb user
myself.

For maintainance, once the switch to bbdb 3 is done and fully fixed, the
incoming bugs should be more locals to helm-bbdb or related to helm, and
I could fix them if necessary (users can send PR too).

Thanks.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> Are you sure you are using helm-bbdb and not just the original bbdb
> commands helmized by helm-mode ?

Yes, I meant the helmized bbdb commands.  I never used helm-bbdb.

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> If you are using bbdb version 3+ it would be welcome. The problem is
> just the new bbdb is not backward compatible with old version and I
> don't know which functions to use with new bbdb, not being a bbdb user
> myself.

It doesn't seem to be difficult, I got most of the stuff working again
after switching to the new names of some functions.  Will make a PR
soon.

**Comment by michael-heerdegen** [comment]
@thierryvolpiatto I updated helm-bbdb and fixed some small issues; it seems to work again.  Anybody here: if you want to give it a try it...please do.

Then I guess we can add it to Melpa again.
