### ISSUE TITLE
Can't kill buffers whose name has newlines

### ISSUE THREAD

**Issue by uu1101** [emacs-helm/helm#824]
Steps to reproduce:

Create a buffer wose name has newlines:
~~~
(generate-new-buffer "abc
cde")
~~~

Then, try to kill it with <kbd>C-x k</kbd>.

The following error occurs: `No buffer named abc`.

**Comment by tuhdo** [comment]
Using `helm-mini` or `helm-buffers-list` and press `C-c d`, you can kill those. But yes, Helm needs to handle this case where Helmizied commands have newlines in its names.

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> Using helm-mini or helm-buffers-list and press C-c d, you can kill
> those. But yes, Helm needs to handle this case where Helmizied
> commands have newlines in its names.

Helmized commands for buffer is C-x b and have no action except jumping
to buffer, and should not have other actions.

IMO what OP is reporting is probably an emacs bug with some emacs
version ?

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
No, it's not an emacs bug. C-x k with helm-mode off can kill the buffer.  With helm-mode on, it's not possible.

Try in helm.sh

```
(generate-new-buffer "abc
cde")

(read-buffer "--> ")
```

And try to select the buffer.

The general problem is probably that helm--completing-read-default doesn't correctly treat canidates with newlines:

```
(helm--completing-read-default "Select: " '("aaa\nbbb"))
```

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> The general problem is probably that helm--completing-read-default doesn't correctly treat canidates with newlines:
>
> (helm--completing-read-default "Select: " '("aaa\nbbb"))

It is not helm--completing-read-default which doesn't handle this but
helm itself.
The multiline slot should be used in such cases.
It is just that helm-mode is not detecting if that is needed or not,
because it is really not common to have for example a buffer name with a
newline.

BTW helm--completing-read-default is not public API and should not be
used, use instead completing-read with helm-mode enabled.
 
-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
Yes.  The helm--completing-read-default example was just for demonstration.

**Comment by michael-heerdegen** [comment]
IMHO the distinction between "normal" and multiline is a bit artificial. AFAIKT they are not treated much differently when used, the distinction is mainly about using separator lines in the completions buffer.

What would happen if we would use multiline as default?  We could give the separator strings an appropriate invisible text property.  buffer-invisibility-spec is initialized so that all separators are invisible. When helm finds a candidate including a newline while collecting matches, it modifies buffer-invisibility-spec so that the separators appear.

**Comment by thierryvolpiatto** [comment]
Now such buffers will appear in helm as "ab->cd" on one line and you will be able to kill/switch etc...

**Comment by uu1101** [comment]
Works fine, thank you!
