### ISSUE TITLE
helm-apropos is slow

### ISSUE THREAD

**Issue by c02y** [emacs-helm/helm#854]
`helm-apropos`  is slow, it takes more than 2 seconds to show commands-functions-variables-and-faces list window, but `C-h v` and `C-h f` are instantly. 

Is is possible to make it faster?

**Comment by thierryvolpiatto** [comment]
c02y <notifications@github.com> writes:

> helm-apropos is slow, it takes more than 2 seconds to show commands-functions-variables-and-faces list window, but C-h v and C-h f are instantly.
>
> Is is possible to make it faster?

No, because it is filtering a lot of things, class, methods, types
etc... You can't compare with C-h v/f which is listing symbols with no
filtering. Once started it is fast anyway.
If you are not interested by classes and methods you can filter out them
with `helm-apropos-function-list', it will be faster to start.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by c02y** [comment]
I know it is filtering a lot of things, but it can be slow at the first time, if it can be cached, it will be much faster when you call it later, because I use it a lot.

Caching it can be a new feature.

**Comment by michael-heerdegen** [comment]
AFAIK it is not so much the filtering that makes it slow, but the fact that we want to provide regexp matching and must perform completion from Lisp. We do that via candidates buffer(s), which is fast, but causes a cost of an initial delay.  The delay is long in this case because there are so many candidates.

FWIW, the delay could be avoided by using vanilla completion via completion-regexp-list instead of candidates-in-buffer. We can't do that now however because it is a quite new feature.

Reusing the buffer would solve the problem, but the fact that the candidates list can be outdated could be quite confusing OTOH.

**Comment by michael-heerdegen** [comment]
The above PR effectively minimizes the delay caused by filling the candidates buffers, at least in trunk.

Compare
```
(benchmark
 1
 '(with-temp-buffer
    (cl-loop with all = (all-completions "" obarray)
             for sym in all
             for s = (intern sym)
             unless (keywordp s)
             do (insert (concat sym "\n")))))

==> 1.4s
```
and
```
(benchmark
 1
 '(with-temp-buffer
    (insert (mapconcat
             (lambda (name) (let ((s (intern name)))
                         (if (keywordp s)
                             "" name)))
             (all-completions "" obarray) "\n"))))
==> 0.1 s
```

It may be worth to do something similar in other places at well.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> The above PR effectively minimizes the delay caused by filling the candidates buffers, at least in trunk.

Good catch, thanks.

> It may be worth to do something similar in other places at well.

Done, all in-buffer sources using helm-init-candidates-in-buffer will
benefit from this optimization.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by lewang** [comment]
@michael-heerdegen This is a very nice find.  :+1:
