### ISSUE TITLE
helm reverts to previous matches when space is entered after second pattern

### ISSUE THREAD

**Issue by ahanwadi** [emacs-helm/helm#879]
I am seeing strange behavior in both helm-switch-buffer and helm-find-file. When I enter first two patterns, it correctly shows the matching files/buffers (e.g. "@Scala Hello") but as soon as I enter space after the second pattern, it reverts the list of matches to those matching the first pattern only.

**Comment by ahanwadi** [comment]
![image](https://cloud.githubusercontent.com/assets/1645382/6315071/32671420-b9ab-11e4-916f-9bbc2238df96.png)

**Comment by ahanwadi** [comment]
![image](https://cloud.githubusercontent.com/assets/1645382/6315072/4bb5e06e-b9ab-11e4-9a2c-a450e755035c.png)

**Comment by thierryvolpiatto** [comment]
ahanwadi <notifications@github.com> writes:

> I am seeing strange behavior in both helm-switch-buffer and
> helm-find-file. When I enter first two patterns, it correctly shows
> the matching files/buffers (e.g. " @Scala Hello") but as soon as I
> enter space after the second pattern, it reverts the list of matches
> to those matching the first pattern only.

Because it is waiting for new input after "hello ", so it takes only in
account "*scala" and ignore "hello " waiting you enter some more
character after the space.
Here if I type:

"*lisp ^helm"

helm list all (e)lisp buffers with name starting with "helm".

if I add a space: "*lisp ^helm "

helm ignore "^helm" and list only the (e)lisp buffer waiting you
complete the search pattern after "^helm ".

As soon I enter "*lisp ^helm fi"

helm complete as expected.

Hope that's clear.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by ahanwadi** [comment]
Makes sense now.
