### ISSUE TITLE
No way to adaptive sort locate results

### ISSUE THREAD

**Issue by dberlin** [emacs-helm/helm#963]
It would be really nice if one could adaptive sort the helm-source-locate results.
Trying to use helm-adaptive-sort as a candidate transformer, however, fails miserably.

**Comment by thierryvolpiatto** [comment]
I disagree on this, adaptative have not be used in such source.

**Comment by dberlin** [comment]
Can you explain why?
I use locate all the time to quickly get to files that are in 5-6  very different directory trees, so navigation would be a pain in the ass to get to, and history is also a pain in the ass because order is random.
(Better suggestions on how to accomplish this workflow very welcome)

It seems quite silly that i can't make the order of those results change based on how often i select them, so that those 5-6 appear at the top.

**Comment by thierryvolpiatto** [comment]
Daniel Berlin <notifications@github.com> writes:

> I use locate all the time to quickly get to files that are in 5-6 very
> different directory trees, so navigation would be a pain in the ass to
> get to, and history is also a pain in the ass because order is random.

Which history? if you use helm-find-files and C-c h you have the hitory
of all visited files in the more recent order.

> (Better suggestions on how to accomplish this workflow very welcome)

Use a local db in each directories if you really want to use locate for
this, otherwise, use helm-find-files+C-c h.
Also keep always the buffers of those files open.

> It seems quite silly that i can't make the order of those results
> change based on how often i select them, so that those 5-6 appear at
> the top.

What is silly is to use locate to reach files where you already know the
location and BTW are in history or recentf.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by dberlin** [comment]
The recent files and history of course, will have thousands of other files in the way of these 5 as i look around at definitions of code and navigate around.  They are *also* sorted by recency, instead of how often i access them, because i can't adaptively sort *that* either.

You can call this use case silly, but you still haven't explained why adaptive sorting it is a bad idea.
IE what bad thing happens if you let it happen.
