### ISSUE TITLE
Helm-Find-Files takes more than 30 sec to start in Windows 8

### ISSUE THREAD

**Issue by rafaelgp** [emacs-helm/helm#974]
Hello,

I'm using Emacs 25.1 in Windows 8.
You can see my emacs configuration here: https://github.com/rafaelgp/emacs-config
I load helm using 'use-package' which calls 'helm-config'

Emacs starts relatively quickly (7 seconds) but the first time I use 'helm-find-files' or 'helm-recentf' it takes 32 seconds to start working. Emacs stays in stand by during this time and I can't do anything but wait and see.
After this first call, helm is very quick and if I use 'helm-find-files' it starts intermediately.

I understand that the first time I use it, helm is loading 'helm-files' libraries, and that's what it takes 32 seconds.
Using same emacs configuration in my Virtualbox machine (Debian with Emacs 24.4.1) the first time I use 'helm-find-files' it takes only 3 seconds to start working. I wonder, why does it take 10 times more time in Windows?

Thanks.

**Comment by tuhdo** [comment]
Does it happen with only `helm` installed from stock Emacs? I see that you defer loading of other Helm packages and when you invoke a Helm command, those packages are also loaded which may increase the loading time.

>  I wonder, why does it take 10 times more time in Windows?

Emacs on Windows is much slower on Linux. My old config took 10 seconds to load on my Ubuntu machine and it took 80 seconds to load on my Windows machine. That's why I'm using [Spacemacs](https://github.com/syl20bnr/spacemacs) now since they really did a good job at optimizing startup time: 1.5s on my Ubuntu machine and 10s (with Helm loaded) on my WIndows machine and it has more than 100 built-in packages.

@thierryvolpiatto the relevant section is [here](https://github.com/rafaelgp/emacs-config/blob/master/setup/setup_packages.el#L329).

**Comment by thierryvolpiatto** [comment]
RafaelGP <notifications@github.com> writes:

> Hello,
>
> I'm using Emacs 25.1 in Windows 8.  You can see my emacs configuration
> here: https://github.com/rafaelgp/emacs-config I load helm using
> 'use-package' which calls 'helm-config'

Use a minimal config and see what happen.

Generally expect strange things happen when using a development version
of emacs (especially on Windoze and even more on 8).

I have no access to Windows8 so I can't reproduce.

Also on debian helm-find-files should start instantaneously (not 3s).
Same try a minimal config (use ./emacs-helm.sh there).

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by rafaelgp** [comment]
Aha! I think we're onto something here!
I tried using a minimum configuration and it only took 4 seconds.
I'll try to find out what is it what it's slowing down helm.

>Does it happen with only helm installed from stock Emacs? I see that you defer loading of other Helm packages and when you invoke a Helm command, those packages are also loaded which may increase the loading time

That's not it. I tried by removing all the :defer but it didn't make any difference.

**Comment by rafaelgp** [comment]
Found it! This is the line causing all the trouble

  (add-to-list 'exec-path "C:\\msys64\\usr\\bin")

A directory containing 532 files:
82 bash 
346.exe
104.dll

After removing that line from my configuration file, helm-find-file only takes 4 seconds to start.

Thanks!
